#ifndef GDCC_COROUTINE_H
#define GDCC_COROUTINE_H

/// GDCC coroutine runtime helpers on top of the vendored minicoro stackful coroutine
/// library. Contract: doc/gdcc_runtime_lib.md §Coroutine Runtime and
/// doc/gdcc_ownership_lifecycle_spec.md §3.10.
///
/// This header is generic: everything per-coroutine-function (state class wrapper,
/// ClassDB registration, typed-slot callbacks) is generated by the backend templates;
/// only the shared logic lives here.

#include <godot_binding.h>
#include "minicoro.h"

/// Magic value validated by `gdcc_coro_state_identify` to recognize GDCC coroutine state
/// object bindings. ASCII "GDCCOROS".
#define GDCC_CORO_STATE_MAGIC UINT64_C(0x474443434F524F53)

/// Centralized coroutine stack reservation (1 MiB). Engine calls (Variant/ClassDB/regex/
/// JSON...) execute on the coroutine stack, so stack depth is not statically bounded; with
/// the vmem allocator the reservation is address space, not committed memory.
#define GDCC_CORO_STACK_SIZE ((size_t)1024u * 1024u)

typedef struct gdcc_coro_state_header gdcc_coro_state_header;

/// Per-state-class descriptor with generated callbacks, so this generic TU never touches
/// typed frame fields. Generated once per coroutine function by the backend templates.
typedef struct gdcc_coro_state_desc {
    /// Finalize step 1: COPY (not move) the typed return slot into `result_cache`; the slot
    /// stays alive afterwards for typed waiters and the done fast path. Void coroutines
    /// leave `result_cache` as nil. Always non-NULL in generated code.
    void (*pack_result)(gdcc_coro_state_header *state);
    /// Copy the typed return slot into the awaiter's typed result storage (`out_typed`
    /// points at the awaiter's default-initialized slot; slot-write discipline applies).
    /// Void coroutines write a constructed nil Variant. Always non-NULL in generated code.
    void (*copy_ret_slot)(gdcc_coro_state_header *state, void *out_typed);
    /// Destroy the typed return slot content in place. Called exactly once from the
    /// generated `free_instance` - NEVER from the cancel path - and must tolerate a
    /// never-written or moved-from slot. Always non-NULL in generated code.
    void (*destroy_ret_slot)(gdcc_coro_state_header *state);
    /// Finalize step 4: emit `completed(result_cache)` on `state->obj`.
    void (*emit_completed)(gdcc_coro_state_header *state);
} gdcc_coro_state_desc;

/// Waiter output channel kind: the static internal ABI hands results over through the
/// typed `copy_ret_slot` callback (zero Variant round-trip), while dynamic-path awaiters
/// receive one private `godot_variant_new_copy` of `result_cache` each.
typedef enum gdcc_coro_waiter_kind {
    GDCC_CORO_WAITER_VARIANT, // out is a godot_Variant *
    GDCC_CORO_WAITER_TYPED    // out is the awaiter's typed result slot address
} gdcc_coro_waiter_kind;

/// One suspended awaiter registered on a callee state object. The node owns a strong
/// reference to the awaiter state object (callee -> awaiter keep-alive edge), released only
/// by `gdcc_coro_finalize` (after resuming the awaiter) or `gdcc_coro_cancel` (never
/// resuming). Nodes are pushed at the head; multiple waiters resume in LIFO order.
typedef struct gdcc_coro_waiter {
    struct gdcc_coro_waiter *next;
    gdcc_coro_waiter_kind kind; // selects the resume-value channel for `out`
    mco_coro *co;               // awaiter coroutine to resume
    void *out;                  // awaiter result storage (kind-selected); written exactly once by finalize
    GDExtensionObjectPtr awaiter; // strong edge to the awaiter state object (NULL in pure-C fixtures)
    // Awaiter frame header, used to cascade `gdcc_coro_finalize` when the resumed awaiter
    // returned MCO_DEAD. The strong `awaiter` edge above also keeps this node itself valid:
    // a registered awaiter can never reach PREDELETE, so `co`/`out` never dangle.
    gdcc_coro_state_header *awaiter_state;
} gdcc_coro_waiter;

/// Common frame header embedded in every hidden coroutine state class wrapper. The wrapper
/// root field is `_object` (no GDCC `_super` chain); this header follows it and is exposed
/// through the dedicated binding token, never at wrapper offset 0.
struct gdcc_coro_state_header {
    uint64_t magic;                   // GDCC_CORO_STATE_MAGIC while the wrapper is live
    const gdcc_coro_state_desc *desc; // per-class generated callbacks
    GDExtensionObjectPtr obj;         // back-pointer to the state object, filled at creation
    mco_coro *co;                     // NULL until the entry thunk creates the coroutine
    bool done;                        // finalize published result_cache
    bool cancel;                      // cancel-resume requested (mutually exclusive with done)
    godot_Variant result_cache;       // always constructed; zeroed storage is a nil Variant
    gdcc_coro_waiter *waiters;        // head of the waiter list
};

/// Address of a gdcc_coroutine.c-internal global, used as the dedicated instance-binding
/// token shared by generated state-class `create_instance2` code and
/// `gdcc_coro_state_identify`. Distinct per loaded gdcc module, so foreign gdcc state
/// objects fall through to the external-object duck-type path.
void *gdcc_coro_binding_token(void);

/// Initializes the common header of a freshly created state object (called from the
/// generated `POSTINITIALIZE` path after the wrapper storage is zeroed). `result_cache`
/// ends up as a constructed nil Variant.
void gdcc_coro_state_header_init(gdcc_coro_state_header *state, const gdcc_coro_state_desc *desc, GDExtensionObjectPtr obj);

/// O(1) pure-C recognition of a GDCC coroutine state object: dedicated token binding plus
/// magic validation. Returns the header pointer, or NULL for any non-state object.
gdcc_coro_state_header *gdcc_coro_state_identify(GDExtensionObjectPtr obj);

/// Tears down the generic frame parts from the state class `free_instance`: the coroutine
/// must be MCO_DEAD by contract (cancel-resume at PREDELETE guarantees it) or NULL (the
/// entry thunk reported OOM before `mco_create`); destroys the coroutine stack and the
/// always-constructed `result_cache`, and revokes the magic so a dangling binding can never
/// be re-identified. The typed return slot (destroyed exactly once via
/// `desc->destroy_ret_slot`), typed parameter fields and the wrapper itself remain
/// generated-code responsibilities.
void gdcc_coro_state_free(gdcc_coro_state_header *state);

/// Compiler-local slot helpers backing the `compiler::GdccCoroState` LIR variable type: an
/// OWNED coroutine state object reference stored as `godot_Object *`. Generated code
/// initializes every such local via `_slot_init` in `__prepare__` (call-and-assign shape:
/// `$slot = gdcc_coro_state_slot_init();`) and destroys it via `_slot_destroy` from
/// `destruct` / `__finally__`; `await` resets a consumed slot to NULL (moved-from), so the
/// destroy helper tolerates NULL content.
godot_Object *gdcc_coro_state_slot_init(void);

/// Releases the OWNED state object reference held by the slot (RefCounted unreference;
/// reaching zero drives the PREDELETE cancel path through object destruction) and resets
/// the slot to NULL. A non-NULL value that is not a GDCC coroutine state object is a
/// compiler bug: the single-consumer LIR contract guarantees only state references or NULL
/// ever reach this slot.
void gdcc_coro_state_slot_destroy(godot_Object **slot);

/// Awaits a statically typed Signal: connects one-shot with a custom Callable holding a
/// strong reference to the awaiter's own state object (the final keep-alive edge of a
/// suspended coroutine), then yields. The signal callback writes `*out` per the
/// resume-value rule (0 args -> nil, 1 arg -> the argument, N args -> Array of all;
/// callback arguments are only copied, never consumed) and resumes the coroutine.
/// Connect failure is a deliberate deviation from Godot's hang-forever: runtime error,
/// nil into `out`, and return WITHOUT suspending.
/// After this function returns, generated code must check `self->cancel` before reading
/// `out` (a cancel-resume returns without `out` being written).
void gdcc_coro_await_signal(godot_Signal *sig, godot_Variant *out, mco_coro *co, gdcc_coro_state_header *self);

/// Awaits another GDCC coroutine's state object (static internal-ABI path).
/// `callee->done` copies the typed return slot through `desc->copy_ret_slot` and returns
/// immediately (connect-after-done fast path, no suspend). Otherwise registers a
/// typed-waiter `{co, out_typed, strong ref to self->obj}` on the callee's waiter list and
/// yields; `gdcc_coro_finalize` writes `out_typed` through the same callback and resumes.
/// Same `self->cancel` post-condition as `gdcc_coro_await_signal`.
/// `out_typed` points at the awaiter's default-initialized typed result slot; failure
/// paths (NULL/cancelled callee, waiter allocation OOM) report a runtime error and leave
/// it untouched, so the slot keeps its `__prepare__` default - there is no typed nil.
///
/// CONSUME CONTRACT: this call always consumes the call site's OWNED reference to the
/// callee state object (`callee->obj`). On every path the reference is released before the
/// coroutine may yield, so the awaiter never holds the callee across a suspension - the
/// keep-alive graph stays a DAG (callee -> awaiter only) and the abandonment cascade stays
/// reachable. The caller must not touch its callee reference after this call.
void gdcc_coro_await_state(gdcc_coro_state_header *callee, void *out_typed, mco_coro *co, gdcc_coro_state_header *self);

/// Awaits a Variant operand (dynamic path), three-layer dispatch:
/// 1. TYPE_SIGNAL -> extract and delegate to `gdcc_coro_await_signal`.
/// 2. TYPE_OBJECT -> null payload passes through; freed object reports
///    "Trying to await on a freed object." (Godot-aligned), fills nil, no suspend;
///    a live object is run through `gdcc_coro_state_identify`: own state objects go
///    through the shared waiter-channel core (`gdcc_coro_register_waiter` - NOT
///    `gdcc_coro_await_state`, which would release the callee reference a second time),
///    external objects connect one-shot to `Signal(obj, "completed")` where the connect
///    error code IS the existence check - objects without that signal pass the operand
///    through (deliberately wider duck-type than Godot's internal function-state class
///    check), while a pre-connect allocation failure reports an error instead of
///    passing through.
/// 3. Any other type (including nil) -> pass through: copy the operand into `out`.
/// Same `self->cancel` post-condition as `gdcc_coro_await_signal`.
///
/// OPERAND EDGE CONTRACT: on the own-state-object suspend path the callee reference held by
/// `operand` is released and `operand` is reset to nil before yielding (same no-cycle rule
/// as `gdcc_coro_await_state`). Everywhere else `operand` is left untouched: pass-through
/// paths copy it, and the external-object path deliberately keeps the emitter Variant
/// retained in the awaiter frame for the whole suspension (Godot-aligned keep-alive
/// direction).
void gdcc_coro_await_dynamic(godot_Variant *operand, godot_Variant *out, mco_coro *co, gdcc_coro_state_header *self);

/// The single completion exit, called only from `mco_resume` return points that observed
/// MCO_DEAD (entry thunk, signal callback, waiter cascade). Never entered from the cancel
/// path. Invariant order: (1) COPY the typed return slot into `result_cache` via
/// `desc->pack_result` - the slot stays alive for the typed channel; (2) publish `done`;
/// (3) pop waiters - typed waiters receive the result through `desc->copy_ret_slot`,
/// Variant waiters through one `godot_variant_new_copy` of `result_cache` each, resume the
/// waiter, cascade `gdcc_coro_finalize` when the resumed waiter returned MCO_DEAD, and only
/// then release the reference edge; (4) `desc->emit_completed` last for external listeners.
/// Re-entrant by design: waiter resumes may cascade nested finalizes, and the early `done`
/// publication makes nested entry on the same state a no-op.
void gdcc_coro_finalize(gdcc_coro_state_header *state);

/// The abandonment path, mutually exclusive with `gdcc_coro_finalize`; hooked from the
/// state class NOTIFICATION_PREDELETE (never from `free_instance`). No-op when `done` or
/// already cancelled. Otherwise: set `cancel`, resume a MCO_SUSPENDED coroutine so the
/// body jumps to `__finally__` at the nearest await resume point and returns MCO_DEAD.
/// Never finalizes: no `done`, no pack, no emit, and waiters are only popped to release
/// their reference edges - abandoned awaiters stay suspended forever (aligned with Godot
/// `cancel_pending_functions`). Never touches the typed return slot: the cancel-path
/// default written by the body's `__finally__` is destroyed by the generated
/// `free_instance` (exactly one `desc->destroy_ret_slot` per state). Tolerates
/// `co == NULL` (state object died before `mco_create`, e.g. OOM in the entry thunk).
void gdcc_coro_cancel(gdcc_coro_state_header *state);

#endif //GDCC_COROUTINE_H
