/* This file was generated by GodotBindingTool. */
/* Do not edit by hand. */
#ifndef GDCC_GODOT_NATIVE_STRUCTURES_H
#define GDCC_GODOT_NATIVE_STRUCTURES_H

#include <godot_builtin_types.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum godot_TextServer_Direction {
    godot_TextServer_DIRECTION_AUTO = 0,
    godot_TextServer_DIRECTION_LTR = 1,
    godot_TextServer_DIRECTION_RTL = 2,
    godot_TextServer_DIRECTION_INHERITED = 3,
} godot_TextServer_Direction;

typedef struct godot_AudioFrame {
    float left;
    float right;
} godot_AudioFrame;

typedef struct godot_CaretInfo {
    godot_Rect2 leading_caret;
    godot_Rect2 trailing_caret;
    godot_TextServer_Direction leading_direction;
    godot_TextServer_Direction trailing_direction;
} godot_CaretInfo;

typedef struct godot_Glyph {
    int start;
    int end;
    uint8_t count;
    uint8_t repeat;
    uint16_t flags;
    float x_off;
    float y_off;
    float advance;
    godot_RID font_rid;
    int font_size;
    int32_t index;
} godot_Glyph;

typedef struct godot_ObjectID {
    uint64_t id;
} godot_ObjectID;

typedef struct godot_PhysicsServer2DExtensionMotionResult {
    godot_Vector2 travel;
    godot_Vector2 remainder;
    godot_Vector2 collision_point;
    godot_Vector2 collision_normal;
    godot_Vector2 collider_velocity;
    godot_real_t collision_depth;
    godot_real_t collision_safe_fraction;
    godot_real_t collision_unsafe_fraction;
    int collision_local_shape;
    godot_ObjectID collider_id;
    godot_RID collider;
    int collider_shape;
} godot_PhysicsServer2DExtensionMotionResult;

typedef struct godot_PhysicsServer2DExtensionRayResult {
    godot_Vector2 position;
    godot_Vector2 normal;
    godot_RID rid;
    godot_ObjectID collider_id;
    godot_Object * collider;
    int shape;
} godot_PhysicsServer2DExtensionRayResult;

typedef struct godot_PhysicsServer2DExtensionShapeRestInfo {
    godot_Vector2 point;
    godot_Vector2 normal;
    godot_RID rid;
    godot_ObjectID collider_id;
    int shape;
    godot_Vector2 linear_velocity;
} godot_PhysicsServer2DExtensionShapeRestInfo;

typedef struct godot_PhysicsServer2DExtensionShapeResult {
    godot_RID rid;
    godot_ObjectID collider_id;
    godot_Object * collider;
    int shape;
} godot_PhysicsServer2DExtensionShapeResult;

typedef struct godot_PhysicsServer3DExtensionMotionCollision {
    godot_Vector3 position;
    godot_Vector3 normal;
    godot_Vector3 collider_velocity;
    godot_Vector3 collider_angular_velocity;
    godot_real_t depth;
    int local_shape;
    godot_ObjectID collider_id;
    godot_RID collider;
    int collider_shape;
} godot_PhysicsServer3DExtensionMotionCollision;

typedef struct godot_PhysicsServer3DExtensionMotionResult {
    godot_Vector3 travel;
    godot_Vector3 remainder;
    godot_real_t collision_depth;
    godot_real_t collision_safe_fraction;
    godot_real_t collision_unsafe_fraction;
    godot_PhysicsServer3DExtensionMotionCollision collisions[32];
    int collision_count;
} godot_PhysicsServer3DExtensionMotionResult;

typedef struct godot_PhysicsServer3DExtensionRayResult {
    godot_Vector3 position;
    godot_Vector3 normal;
    godot_RID rid;
    godot_ObjectID collider_id;
    godot_Object * collider;
    int shape;
    int face_index;
} godot_PhysicsServer3DExtensionRayResult;

typedef struct godot_PhysicsServer3DExtensionShapeRestInfo {
    godot_Vector3 point;
    godot_Vector3 normal;
    godot_RID rid;
    godot_ObjectID collider_id;
    int shape;
    godot_Vector3 linear_velocity;
} godot_PhysicsServer3DExtensionShapeRestInfo;

typedef struct godot_PhysicsServer3DExtensionShapeResult {
    godot_RID rid;
    godot_ObjectID collider_id;
    godot_Object * collider;
    int shape;
} godot_PhysicsServer3DExtensionShapeResult;

typedef struct godot_ScriptLanguageExtensionProfilingInfo {
    godot_StringName signature;
    uint64_t call_count;
    uint64_t total_time;
    uint64_t self_time;
} godot_ScriptLanguageExtensionProfilingInfo;

#ifdef __cplusplus
}
#endif

#endif
