/* This file was generated by GodotBindingTool. */
/* Do not edit by hand. */
#ifndef GDCC_GODOT_FIXED_BINDING_H
#define GDCC_GODOT_FIXED_BINDING_H

#include <godot_utility.h>

#ifdef __cplusplus
extern "C" {
#endif

GDCC_GODOT_DECL godot_Engine * godot_Engine_singleton(void);
GDCC_GODOT_DECL godot_bool godot_Engine_is_editor_hint(godot_Engine * self);
GDCC_GODOT_DECL godot_ClassDB * godot_ClassDB_singleton(void);
GDCC_GODOT_DECL godot_bool godot_ClassDB_is_parent_class(godot_ClassDB * self, const godot_StringName * class_name, const godot_StringName * inherits);
GDCC_GODOT_DECL godot_Variant godot_Object_call(GDExtensionObjectPtr self, const godot_StringName * method, const godot_Variant ** argv, godot_int argc);
GDCC_GODOT_DECL godot_Variant godot_Object_get(GDExtensionConstObjectPtr self, const godot_StringName * property);
GDCC_GODOT_DECL void godot_Object_set(GDExtensionObjectPtr self, const godot_StringName * property, const godot_Variant * value);
GDCC_GODOT_DECL godot_int godot_Object_get_instance_id(GDExtensionConstObjectPtr self);
GDCC_GODOT_DECL void godot_Object_notification(GDExtensionObjectPtr self, godot_int what, godot_bool reversed);
GDCC_GODOT_DECL godot_int godot_Object_NOTIFICATION_POSTINITIALIZE(void);
GDCC_GODOT_DECL godot_int godot_Object_NOTIFICATION_PREDELETE(void);
GDCC_GODOT_DECL godot_bool godot_RefCounted_reference(godot_RefCounted * self);
GDCC_GODOT_DECL godot_bool godot_RefCounted_unreference(godot_RefCounted * self);
GDCC_GODOT_DECL godot_bool godot_RefCounted_init_ref(godot_RefCounted * self);

#ifdef __cplusplus
}
#endif

#endif
