/* This file was generated by GodotInterfaceGenerator. */
/* Do not edit by hand. */
#include "godot_binding.h"
#include "godot_interface.c"
#include "godot_builtin.c"
#include "godot_utility.c"
#include "godot_fixed_binding.c"
