/* This file was generated by GodotBindingTool. */
/* Do not edit by hand. */
#ifndef GDCC_GODOT_MACROS_H
#define GDCC_GODOT_MACROS_H

#include <stddef.h>

#if !defined(GDE_EXPORT)
#if defined(_WIN32)
#define GDE_EXPORT __declspec(dllexport)
#elif defined(__GNUC__)
#define GDE_EXPORT __attribute__((visibility("default")))
#else
#define GDE_EXPORT
#endif
#endif

#if defined(__cplusplus)
#define GDCC_GODOT_STATIC_ASSERT(condition, message) static_assert(condition, message)
#elif defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#include <assert.h>
#define GDCC_GODOT_STATIC_ASSERT(condition, message) static_assert(condition, message)
#else
#define GDCC_GODOT_STATIC_ASSERT(condition, message)
#endif

#if defined(_MSC_VER)
#define GDCC_GODOT_DECL
#elif defined(__GNUC__)
#define GDCC_GODOT_DECL __attribute__((__visibility__("hidden")))
#else
#define GDCC_GODOT_DECL
#endif

#define GDCC_GODOT_INLINE static inline
#define GDCC_GODOT_OPAQUE_STRUCT(name) typedef struct name name
#define GDCC_GODOT_ASSERT_SIZE(type) \
    GDCC_GODOT_STATIC_ASSERT(sizeof(godot_##type) == GDCC_GODOT_SIZE_##type, \
                             "Incompatible size for " #type)
#define GDCC_GODOT_ASSERT_LAYOUT(type, member) \
    GDCC_GODOT_STATIC_ASSERT(offsetof(godot_##type, member) == GDCC_GODOT_OFFSET_##type##_##member, \
                             "Incompatible offset for " #type "." #member); \
    GDCC_GODOT_STATIC_ASSERT(sizeof(((godot_##type *)0)->member) == sizeof(GDCC_GODOT_META_##type##_##member), \
                             "Incompatible meta layout for " #type "." #member)

#endif
