/* This file was generated by GodotInterfaceGenerator. */
/* Do not edit by hand. */
#include "godot_interface.h"

#include <stdarg.h>
#include <stdio.h>

/*
 * This pointer table is declared in the header so inline wrappers across all
 * translation units share the eager-resolved state initialized below.
 */
static GDExtensionInterfacePrintError gdcc_lookup_fail_print_error = NULL;
static GDExtensionInterfacePrintErrorWithMessage gdcc_lookup_fail_print_error_with_message = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceGetGodotVersion gdcc_interface_get_godot_version = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceGetGodotVersion2 gdcc_interface_get_godot_version2 = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceMemAlloc gdcc_interface_mem_alloc = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceMemRealloc gdcc_interface_mem_realloc = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceMemFree gdcc_interface_mem_free = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePrintError gdcc_interface_print_error = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePrintErrorWithMessage gdcc_interface_print_error_with_message = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePrintWarning gdcc_interface_print_warning = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePrintWarningWithMessage gdcc_interface_print_warning_with_message = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePrintScriptError gdcc_interface_print_script_error = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePrintScriptErrorWithMessage gdcc_interface_print_script_error_with_message = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceGetNativeStructSize gdcc_interface_get_native_struct_size = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantNewCopy gdcc_interface_variant_new_copy = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantNewNil gdcc_interface_variant_new_nil = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantDestroy gdcc_interface_variant_destroy = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantCall gdcc_interface_variant_call = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantCallStatic gdcc_interface_variant_call_static = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantEvaluate gdcc_interface_variant_evaluate = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantSet gdcc_interface_variant_set = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantSetNamed gdcc_interface_variant_set_named = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantSetKeyed gdcc_interface_variant_set_keyed = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantSetIndexed gdcc_interface_variant_set_indexed = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGet gdcc_interface_variant_get = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetNamed gdcc_interface_variant_get_named = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetKeyed gdcc_interface_variant_get_keyed = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetIndexed gdcc_interface_variant_get_indexed = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantIterInit gdcc_interface_variant_iter_init = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantIterNext gdcc_interface_variant_iter_next = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantIterGet gdcc_interface_variant_iter_get = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantHash gdcc_interface_variant_hash = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantRecursiveHash gdcc_interface_variant_recursive_hash = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantHashCompare gdcc_interface_variant_hash_compare = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantBooleanize gdcc_interface_variant_booleanize = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantDuplicate gdcc_interface_variant_duplicate = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantStringify gdcc_interface_variant_stringify = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetType gdcc_interface_variant_get_type = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantHasMethod gdcc_interface_variant_has_method = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantHasMember gdcc_interface_variant_has_member = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantHasKey gdcc_interface_variant_has_key = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetObjectInstanceId gdcc_interface_variant_get_object_instance_id = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetTypeName gdcc_interface_variant_get_type_name = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantCanConvert gdcc_interface_variant_can_convert = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantCanConvertStrict gdcc_interface_variant_can_convert_strict = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceGetVariantFromTypeConstructor gdcc_interface_get_variant_from_type_constructor = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceGetVariantToTypeConstructor gdcc_interface_get_variant_to_type_constructor = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceGetVariantGetInternalPtrFunc gdcc_interface_variant_get_ptr_internal_getter = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetPtrOperatorEvaluator gdcc_interface_variant_get_ptr_operator_evaluator = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetPtrBuiltinMethod gdcc_interface_variant_get_ptr_builtin_method = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetPtrConstructor gdcc_interface_variant_get_ptr_constructor = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetPtrDestructor gdcc_interface_variant_get_ptr_destructor = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantConstruct gdcc_interface_variant_construct = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetPtrSetter gdcc_interface_variant_get_ptr_setter = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetPtrGetter gdcc_interface_variant_get_ptr_getter = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetPtrIndexedSetter gdcc_interface_variant_get_ptr_indexed_setter = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetPtrIndexedGetter gdcc_interface_variant_get_ptr_indexed_getter = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetPtrKeyedSetter gdcc_interface_variant_get_ptr_keyed_setter = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetPtrKeyedGetter gdcc_interface_variant_get_ptr_keyed_getter = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetPtrKeyedChecker gdcc_interface_variant_get_ptr_keyed_checker = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetConstantValue gdcc_interface_variant_get_constant_value = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceVariantGetPtrUtilityFunction gdcc_interface_variant_get_ptr_utility_function = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNewWithLatin1Chars gdcc_interface_string_new_with_latin1_chars = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNewWithUtf8Chars gdcc_interface_string_new_with_utf8_chars = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNewWithUtf16Chars gdcc_interface_string_new_with_utf16_chars = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNewWithUtf32Chars gdcc_interface_string_new_with_utf32_chars = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNewWithWideChars gdcc_interface_string_new_with_wide_chars = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNewWithLatin1CharsAndLen gdcc_interface_string_new_with_latin1_chars_and_len = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNewWithUtf8CharsAndLen gdcc_interface_string_new_with_utf8_chars_and_len = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNewWithUtf8CharsAndLen2 gdcc_interface_string_new_with_utf8_chars_and_len2 = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNewWithUtf16CharsAndLen gdcc_interface_string_new_with_utf16_chars_and_len = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNewWithUtf16CharsAndLen2 gdcc_interface_string_new_with_utf16_chars_and_len2 = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNewWithUtf32CharsAndLen gdcc_interface_string_new_with_utf32_chars_and_len = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNewWithWideCharsAndLen gdcc_interface_string_new_with_wide_chars_and_len = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringToLatin1Chars gdcc_interface_string_to_latin1_chars = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringToUtf8Chars gdcc_interface_string_to_utf8_chars = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringToUtf16Chars gdcc_interface_string_to_utf16_chars = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringToUtf32Chars gdcc_interface_string_to_utf32_chars = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringToWideChars gdcc_interface_string_to_wide_chars = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringOperatorIndex gdcc_interface_string_operator_index = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringOperatorIndexConst gdcc_interface_string_operator_index_const = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringOperatorPlusEqString gdcc_interface_string_operator_plus_eq_string = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringOperatorPlusEqChar gdcc_interface_string_operator_plus_eq_char = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringOperatorPlusEqCstr gdcc_interface_string_operator_plus_eq_cstr = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringOperatorPlusEqWcstr gdcc_interface_string_operator_plus_eq_wcstr = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringOperatorPlusEqC32str gdcc_interface_string_operator_plus_eq_c32str = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringResize gdcc_interface_string_resize = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNameNewWithLatin1Chars gdcc_interface_string_name_new_with_latin1_chars = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNameNewWithUtf8Chars gdcc_interface_string_name_new_with_utf8_chars = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceStringNameNewWithUtf8CharsAndLen gdcc_interface_string_name_new_with_utf8_chars_and_len = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceXmlParserOpenBuffer gdcc_interface_xml_parser_open_buffer = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceFileAccessStoreBuffer gdcc_interface_file_access_store_buffer = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceFileAccessGetBuffer gdcc_interface_file_access_get_buffer = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceImagePtrw gdcc_interface_image_ptrw = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceImagePtr gdcc_interface_image_ptr = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceWorkerThreadPoolAddNativeGroupTask gdcc_interface_worker_thread_pool_add_native_group_task = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceWorkerThreadPoolAddNativeTask gdcc_interface_worker_thread_pool_add_native_task = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedByteArrayOperatorIndex gdcc_interface_packed_byte_array_operator_index = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedByteArrayOperatorIndexConst gdcc_interface_packed_byte_array_operator_index_const = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedFloat32ArrayOperatorIndex gdcc_interface_packed_float32_array_operator_index = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedFloat32ArrayOperatorIndexConst gdcc_interface_packed_float32_array_operator_index_const = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedFloat64ArrayOperatorIndex gdcc_interface_packed_float64_array_operator_index = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedFloat64ArrayOperatorIndexConst gdcc_interface_packed_float64_array_operator_index_const = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedInt32ArrayOperatorIndex gdcc_interface_packed_int32_array_operator_index = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedInt32ArrayOperatorIndexConst gdcc_interface_packed_int32_array_operator_index_const = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedInt64ArrayOperatorIndex gdcc_interface_packed_int64_array_operator_index = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedInt64ArrayOperatorIndexConst gdcc_interface_packed_int64_array_operator_index_const = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedStringArrayOperatorIndex gdcc_interface_packed_string_array_operator_index = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedStringArrayOperatorIndexConst gdcc_interface_packed_string_array_operator_index_const = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedVector2ArrayOperatorIndex gdcc_interface_packed_vector2_array_operator_index = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedVector2ArrayOperatorIndexConst gdcc_interface_packed_vector2_array_operator_index_const = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedVector3ArrayOperatorIndex gdcc_interface_packed_vector3_array_operator_index = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedVector3ArrayOperatorIndexConst gdcc_interface_packed_vector3_array_operator_index_const = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedVector4ArrayOperatorIndex gdcc_interface_packed_vector4_array_operator_index = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedVector4ArrayOperatorIndexConst gdcc_interface_packed_vector4_array_operator_index_const = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedColorArrayOperatorIndex gdcc_interface_packed_color_array_operator_index = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePackedColorArrayOperatorIndexConst gdcc_interface_packed_color_array_operator_index_const = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceArrayOperatorIndex gdcc_interface_array_operator_index = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceArrayOperatorIndexConst gdcc_interface_array_operator_index_const = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceArrayRef gdcc_interface_array_ref = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceArraySetTyped gdcc_interface_array_set_typed = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceDictionaryOperatorIndex gdcc_interface_dictionary_operator_index = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceDictionaryOperatorIndexConst gdcc_interface_dictionary_operator_index_const = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceDictionarySetTyped gdcc_interface_dictionary_set_typed = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectMethodBindCall gdcc_interface_object_method_bind_call = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectMethodBindPtrcall gdcc_interface_object_method_bind_ptrcall = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectDestroy gdcc_interface_object_destroy = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceGlobalGetSingleton gdcc_interface_global_get_singleton = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectGetInstanceBinding gdcc_interface_object_get_instance_binding = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectSetInstanceBinding gdcc_interface_object_set_instance_binding = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectFreeInstanceBinding gdcc_interface_object_free_instance_binding = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectSetInstance gdcc_interface_object_set_instance = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectGetClassName gdcc_interface_object_get_class_name = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectCastTo gdcc_interface_object_cast_to = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectGetInstanceFromId gdcc_interface_object_get_instance_from_id = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectGetInstanceId gdcc_interface_object_get_instance_id = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectHasScriptMethod gdcc_interface_object_has_script_method = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectCallScriptMethod gdcc_interface_object_call_script_method = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceRefGetObject gdcc_interface_ref_get_object = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceRefSetObject gdcc_interface_ref_set_object = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceScriptInstanceCreate gdcc_interface_script_instance_create = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceScriptInstanceCreate2 gdcc_interface_script_instance_create2 = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceScriptInstanceCreate3 gdcc_interface_script_instance_create3 = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePlaceHolderScriptInstanceCreate gdcc_interface_placeholder_script_instance_create = NULL;
GDCC_GODOT_DECL GDExtensionInterfacePlaceHolderScriptInstanceUpdate gdcc_interface_placeholder_script_instance_update = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectGetScriptInstance gdcc_interface_object_get_script_instance = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceObjectSetScriptInstance gdcc_interface_object_set_script_instance = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceCallableCustomCreate gdcc_interface_callable_custom_create = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceCallableCustomCreate2 gdcc_interface_callable_custom_create2 = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceCallableCustomGetUserData gdcc_interface_callable_custom_get_userdata = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbConstructObject gdcc_interface_classdb_construct_object = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbConstructObject2 gdcc_interface_classdb_construct_object2 = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbGetMethodBind gdcc_interface_classdb_get_method_bind = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbGetClassTag gdcc_interface_classdb_get_class_tag = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbRegisterExtensionClass gdcc_interface_classdb_register_extension_class = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbRegisterExtensionClass2 gdcc_interface_classdb_register_extension_class2 = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbRegisterExtensionClass3 gdcc_interface_classdb_register_extension_class3 = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbRegisterExtensionClass4 gdcc_interface_classdb_register_extension_class4 = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbRegisterExtensionClass5 gdcc_interface_classdb_register_extension_class5 = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbRegisterExtensionClassMethod gdcc_interface_classdb_register_extension_class_method = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbRegisterExtensionClassVirtualMethod gdcc_interface_classdb_register_extension_class_virtual_method = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant gdcc_interface_classdb_register_extension_class_integer_constant = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbRegisterExtensionClassProperty gdcc_interface_classdb_register_extension_class_property = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbRegisterExtensionClassPropertyIndexed gdcc_interface_classdb_register_extension_class_property_indexed = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbRegisterExtensionClassPropertyGroup gdcc_interface_classdb_register_extension_class_property_group = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbRegisterExtensionClassPropertySubgroup gdcc_interface_classdb_register_extension_class_property_subgroup = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbRegisterExtensionClassSignal gdcc_interface_classdb_register_extension_class_signal = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceClassdbUnregisterExtensionClass gdcc_interface_classdb_unregister_extension_class = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceGetLibraryPath gdcc_interface_get_library_path = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceEditorAddPlugin gdcc_interface_editor_add_plugin = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceEditorRemovePlugin gdcc_interface_editor_remove_plugin = NULL;
GDCC_GODOT_DECL GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8Chars gdcc_interface_editor_help_load_xml_from_utf8_chars = NULL;
GDCC_GODOT_DECL GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8CharsAndLen gdcc_interface_editor_help_load_xml_from_utf8_chars_and_len = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceEditorRegisterGetClassesUsedCallback gdcc_interface_editor_register_get_classes_used_callback = NULL;
GDCC_GODOT_DECL GDExtensionInterfaceRegisterMainLoopCallbacks gdcc_interface_register_main_loop_callbacks = NULL;

static void gdcc_clear_interface_pointers(void) {
    gdcc_lookup_fail_print_error = NULL;
    gdcc_lookup_fail_print_error_with_message = NULL;
    gdcc_interface_get_godot_version = NULL;
    gdcc_interface_get_godot_version2 = NULL;
    gdcc_interface_mem_alloc = NULL;
    gdcc_interface_mem_realloc = NULL;
    gdcc_interface_mem_free = NULL;
    gdcc_interface_print_error = NULL;
    gdcc_interface_print_error_with_message = NULL;
    gdcc_interface_print_warning = NULL;
    gdcc_interface_print_warning_with_message = NULL;
    gdcc_interface_print_script_error = NULL;
    gdcc_interface_print_script_error_with_message = NULL;
    gdcc_interface_get_native_struct_size = NULL;
    gdcc_interface_variant_new_copy = NULL;
    gdcc_interface_variant_new_nil = NULL;
    gdcc_interface_variant_destroy = NULL;
    gdcc_interface_variant_call = NULL;
    gdcc_interface_variant_call_static = NULL;
    gdcc_interface_variant_evaluate = NULL;
    gdcc_interface_variant_set = NULL;
    gdcc_interface_variant_set_named = NULL;
    gdcc_interface_variant_set_keyed = NULL;
    gdcc_interface_variant_set_indexed = NULL;
    gdcc_interface_variant_get = NULL;
    gdcc_interface_variant_get_named = NULL;
    gdcc_interface_variant_get_keyed = NULL;
    gdcc_interface_variant_get_indexed = NULL;
    gdcc_interface_variant_iter_init = NULL;
    gdcc_interface_variant_iter_next = NULL;
    gdcc_interface_variant_iter_get = NULL;
    gdcc_interface_variant_hash = NULL;
    gdcc_interface_variant_recursive_hash = NULL;
    gdcc_interface_variant_hash_compare = NULL;
    gdcc_interface_variant_booleanize = NULL;
    gdcc_interface_variant_duplicate = NULL;
    gdcc_interface_variant_stringify = NULL;
    gdcc_interface_variant_get_type = NULL;
    gdcc_interface_variant_has_method = NULL;
    gdcc_interface_variant_has_member = NULL;
    gdcc_interface_variant_has_key = NULL;
    gdcc_interface_variant_get_object_instance_id = NULL;
    gdcc_interface_variant_get_type_name = NULL;
    gdcc_interface_variant_can_convert = NULL;
    gdcc_interface_variant_can_convert_strict = NULL;
    gdcc_interface_get_variant_from_type_constructor = NULL;
    gdcc_interface_get_variant_to_type_constructor = NULL;
    gdcc_interface_variant_get_ptr_internal_getter = NULL;
    gdcc_interface_variant_get_ptr_operator_evaluator = NULL;
    gdcc_interface_variant_get_ptr_builtin_method = NULL;
    gdcc_interface_variant_get_ptr_constructor = NULL;
    gdcc_interface_variant_get_ptr_destructor = NULL;
    gdcc_interface_variant_construct = NULL;
    gdcc_interface_variant_get_ptr_setter = NULL;
    gdcc_interface_variant_get_ptr_getter = NULL;
    gdcc_interface_variant_get_ptr_indexed_setter = NULL;
    gdcc_interface_variant_get_ptr_indexed_getter = NULL;
    gdcc_interface_variant_get_ptr_keyed_setter = NULL;
    gdcc_interface_variant_get_ptr_keyed_getter = NULL;
    gdcc_interface_variant_get_ptr_keyed_checker = NULL;
    gdcc_interface_variant_get_constant_value = NULL;
    gdcc_interface_variant_get_ptr_utility_function = NULL;
    gdcc_interface_string_new_with_latin1_chars = NULL;
    gdcc_interface_string_new_with_utf8_chars = NULL;
    gdcc_interface_string_new_with_utf16_chars = NULL;
    gdcc_interface_string_new_with_utf32_chars = NULL;
    gdcc_interface_string_new_with_wide_chars = NULL;
    gdcc_interface_string_new_with_latin1_chars_and_len = NULL;
    gdcc_interface_string_new_with_utf8_chars_and_len = NULL;
    gdcc_interface_string_new_with_utf8_chars_and_len2 = NULL;
    gdcc_interface_string_new_with_utf16_chars_and_len = NULL;
    gdcc_interface_string_new_with_utf16_chars_and_len2 = NULL;
    gdcc_interface_string_new_with_utf32_chars_and_len = NULL;
    gdcc_interface_string_new_with_wide_chars_and_len = NULL;
    gdcc_interface_string_to_latin1_chars = NULL;
    gdcc_interface_string_to_utf8_chars = NULL;
    gdcc_interface_string_to_utf16_chars = NULL;
    gdcc_interface_string_to_utf32_chars = NULL;
    gdcc_interface_string_to_wide_chars = NULL;
    gdcc_interface_string_operator_index = NULL;
    gdcc_interface_string_operator_index_const = NULL;
    gdcc_interface_string_operator_plus_eq_string = NULL;
    gdcc_interface_string_operator_plus_eq_char = NULL;
    gdcc_interface_string_operator_plus_eq_cstr = NULL;
    gdcc_interface_string_operator_plus_eq_wcstr = NULL;
    gdcc_interface_string_operator_plus_eq_c32str = NULL;
    gdcc_interface_string_resize = NULL;
    gdcc_interface_string_name_new_with_latin1_chars = NULL;
    gdcc_interface_string_name_new_with_utf8_chars = NULL;
    gdcc_interface_string_name_new_with_utf8_chars_and_len = NULL;
    gdcc_interface_xml_parser_open_buffer = NULL;
    gdcc_interface_file_access_store_buffer = NULL;
    gdcc_interface_file_access_get_buffer = NULL;
    gdcc_interface_image_ptrw = NULL;
    gdcc_interface_image_ptr = NULL;
    gdcc_interface_worker_thread_pool_add_native_group_task = NULL;
    gdcc_interface_worker_thread_pool_add_native_task = NULL;
    gdcc_interface_packed_byte_array_operator_index = NULL;
    gdcc_interface_packed_byte_array_operator_index_const = NULL;
    gdcc_interface_packed_float32_array_operator_index = NULL;
    gdcc_interface_packed_float32_array_operator_index_const = NULL;
    gdcc_interface_packed_float64_array_operator_index = NULL;
    gdcc_interface_packed_float64_array_operator_index_const = NULL;
    gdcc_interface_packed_int32_array_operator_index = NULL;
    gdcc_interface_packed_int32_array_operator_index_const = NULL;
    gdcc_interface_packed_int64_array_operator_index = NULL;
    gdcc_interface_packed_int64_array_operator_index_const = NULL;
    gdcc_interface_packed_string_array_operator_index = NULL;
    gdcc_interface_packed_string_array_operator_index_const = NULL;
    gdcc_interface_packed_vector2_array_operator_index = NULL;
    gdcc_interface_packed_vector2_array_operator_index_const = NULL;
    gdcc_interface_packed_vector3_array_operator_index = NULL;
    gdcc_interface_packed_vector3_array_operator_index_const = NULL;
    gdcc_interface_packed_vector4_array_operator_index = NULL;
    gdcc_interface_packed_vector4_array_operator_index_const = NULL;
    gdcc_interface_packed_color_array_operator_index = NULL;
    gdcc_interface_packed_color_array_operator_index_const = NULL;
    gdcc_interface_array_operator_index = NULL;
    gdcc_interface_array_operator_index_const = NULL;
    gdcc_interface_array_ref = NULL;
    gdcc_interface_array_set_typed = NULL;
    gdcc_interface_dictionary_operator_index = NULL;
    gdcc_interface_dictionary_operator_index_const = NULL;
    gdcc_interface_dictionary_set_typed = NULL;
    gdcc_interface_object_method_bind_call = NULL;
    gdcc_interface_object_method_bind_ptrcall = NULL;
    gdcc_interface_object_destroy = NULL;
    gdcc_interface_global_get_singleton = NULL;
    gdcc_interface_object_get_instance_binding = NULL;
    gdcc_interface_object_set_instance_binding = NULL;
    gdcc_interface_object_free_instance_binding = NULL;
    gdcc_interface_object_set_instance = NULL;
    gdcc_interface_object_get_class_name = NULL;
    gdcc_interface_object_cast_to = NULL;
    gdcc_interface_object_get_instance_from_id = NULL;
    gdcc_interface_object_get_instance_id = NULL;
    gdcc_interface_object_has_script_method = NULL;
    gdcc_interface_object_call_script_method = NULL;
    gdcc_interface_ref_get_object = NULL;
    gdcc_interface_ref_set_object = NULL;
    gdcc_interface_script_instance_create = NULL;
    gdcc_interface_script_instance_create2 = NULL;
    gdcc_interface_script_instance_create3 = NULL;
    gdcc_interface_placeholder_script_instance_create = NULL;
    gdcc_interface_placeholder_script_instance_update = NULL;
    gdcc_interface_object_get_script_instance = NULL;
    gdcc_interface_object_set_script_instance = NULL;
    gdcc_interface_callable_custom_create = NULL;
    gdcc_interface_callable_custom_create2 = NULL;
    gdcc_interface_callable_custom_get_userdata = NULL;
    gdcc_interface_classdb_construct_object = NULL;
    gdcc_interface_classdb_construct_object2 = NULL;
    gdcc_interface_classdb_get_method_bind = NULL;
    gdcc_interface_classdb_get_class_tag = NULL;
    gdcc_interface_classdb_register_extension_class = NULL;
    gdcc_interface_classdb_register_extension_class2 = NULL;
    gdcc_interface_classdb_register_extension_class3 = NULL;
    gdcc_interface_classdb_register_extension_class4 = NULL;
    gdcc_interface_classdb_register_extension_class5 = NULL;
    gdcc_interface_classdb_register_extension_class_method = NULL;
    gdcc_interface_classdb_register_extension_class_virtual_method = NULL;
    gdcc_interface_classdb_register_extension_class_integer_constant = NULL;
    gdcc_interface_classdb_register_extension_class_property = NULL;
    gdcc_interface_classdb_register_extension_class_property_indexed = NULL;
    gdcc_interface_classdb_register_extension_class_property_group = NULL;
    gdcc_interface_classdb_register_extension_class_property_subgroup = NULL;
    gdcc_interface_classdb_register_extension_class_signal = NULL;
    gdcc_interface_classdb_unregister_extension_class = NULL;
    gdcc_interface_get_library_path = NULL;
    gdcc_interface_editor_add_plugin = NULL;
    gdcc_interface_editor_remove_plugin = NULL;
    gdcc_interface_editor_help_load_xml_from_utf8_chars = NULL;
    gdcc_interface_editor_help_load_xml_from_utf8_chars_and_len = NULL;
    gdcc_interface_editor_register_get_classes_used_callback = NULL;
    gdcc_interface_register_main_loop_callbacks = NULL;
}

static const char *gdcc_lookup_text(const char *value) {
    return value != NULL ? value : "<none>";
}

static size_t gdcc_append_lookup_message(
        char *message,
        size_t message_size,
        size_t offset,
        const char *format,
        ...
) {
    if (offset >= message_size) {
        return message_size - 1;
    }
    va_list args;
    va_start(args, format);
    int written = vsnprintf(message + offset, message_size - offset, format, args);
    va_end(args);
    if (written < 0) {
        return offset;
    }
    if ((size_t)written >= message_size - offset) {
        return message_size - 1;
    }
    return offset + (size_t)written;
}

static void gdcc_render_lookup_message(
        const gdcc_binding_lookup_context *context,
        char *message,
        size_t message_size
) {
    size_t offset = gdcc_append_lookup_message(
            message,
            message_size,
            0,
            "kind=%s, function=%s, lookup=%s, owner=%s, type=%s",
            gdcc_lookup_text(context != NULL ? context->kind : NULL),
            gdcc_lookup_text(context != NULL ? context->function_name : NULL),
            gdcc_lookup_text(context != NULL ? context->lookup_name : NULL),
            gdcc_lookup_text(context != NULL ? context->owner : NULL),
            gdcc_lookup_text(context != NULL ? context->type : NULL));
    if (context != NULL && context->has_primary_hash) {
        offset = gdcc_append_lookup_message(
                message,
                message_size,
                offset,
                ", primary_hash=%lld",
                (long long)context->primary_hash);
    } else {
        offset = gdcc_append_lookup_message(message, message_size, offset, ", primary_hash=<none>");
    }
    if (context != NULL && context->compatibility_hash_count > 0) {
        if (context->compatibility_hashes == NULL) {
            gdcc_append_lookup_message(message, message_size, offset, ", compatibility_hashes=<missing>");
            return;
        }
        offset = gdcc_append_lookup_message(message, message_size, offset, ", compatibility_hashes=[");
        for (GDExtensionInt index = 0; index < context->compatibility_hash_count; index++) {
            offset = gdcc_append_lookup_message(
                    message,
                    message_size,
                    offset,
                    index == 0 ? "%lld" : ", %lld",
                    (long long)context->compatibility_hashes[index]);
        }
        gdcc_append_lookup_message(message, message_size, offset, "]");
    } else {
        gdcc_append_lookup_message(message, message_size, offset, ", compatibility_hashes=[]");
    }
}

GDCC_GODOT_DECL GDExtensionBool gdcc_binding_lookup_fail(
        const gdcc_binding_lookup_context *context
) {
    if (context != NULL && context->suppress_internal_error) {
        return false;
    }
    char message[1024];
    gdcc_render_lookup_message(context, message, sizeof(message));
    const char *function_name = gdcc_lookup_text(context != NULL ? context->function_name : NULL);
    const char *lookup_name = gdcc_lookup_text(context != NULL ? context->lookup_name : NULL);
    if (gdcc_lookup_fail_print_error_with_message != NULL) {
        gdcc_lookup_fail_print_error_with_message(
                "GDCC Godot binding lookup failed",
                message,
                function_name,
                lookup_name,
                0,
                true);
    } else if (gdcc_lookup_fail_print_error != NULL) {
        gdcc_lookup_fail_print_error(
                message,
                function_name,
                lookup_name,
                0,
                true);
    }
    fprintf(stderr, "GDCC Godot binding lookup failed: %s\n", message);
    return false;
}

static void gdcc_prepare_lookup_diagnostics(GDExtensionInterfaceGetProcAddress get_proc_address) {
    gdcc_lookup_fail_print_error_with_message =
            (GDExtensionInterfacePrintErrorWithMessage)get_proc_address("print_error_with_message");
    gdcc_lookup_fail_print_error = (GDExtensionInterfacePrintError)get_proc_address("print_error");
}

#define GDCC_RESOLVE_INTERFACE(cache_name, typedef_name, wrapper_literal, lookup_literal) \
    do { \
        cache_name = (typedef_name)get_proc_address(lookup_literal); \
        if (cache_name == NULL) { \
            if (!gdcc_binding_lookup_fail(&(gdcc_binding_lookup_context){ \
                    .kind = "interface", \
                    .function_name = wrapper_literal, \
                    .lookup_name = lookup_literal, \
            })) { \
                goto gdcc_initialize_interface_failed; \
            } \
        } \
    } while (0)

GDCC_GODOT_DECL GDExtensionBool godot_initialize_interface(
        GDExtensionInterfaceGetProcAddress get_proc_address
) {
    gdcc_clear_interface_pointers();
    if (get_proc_address == NULL) {
        return gdcc_binding_lookup_fail(&(gdcc_binding_lookup_context){
                .kind = "interface",
                .function_name = "godot_initialize_interface",
                .lookup_name = "get_proc_address",
        });
    }
    gdcc_prepare_lookup_diagnostics(get_proc_address);
    GDCC_RESOLVE_INTERFACE(gdcc_interface_get_godot_version, GDExtensionInterfaceGetGodotVersion, "godot_get_godot_version", "get_godot_version");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_get_godot_version2, GDExtensionInterfaceGetGodotVersion2, "godot_get_godot_version2", "get_godot_version2");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_mem_alloc, GDExtensionInterfaceMemAlloc, "godot_mem_alloc", "mem_alloc");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_mem_realloc, GDExtensionInterfaceMemRealloc, "godot_mem_realloc", "mem_realloc");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_mem_free, GDExtensionInterfaceMemFree, "godot_mem_free", "mem_free");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_print_error, GDExtensionInterfacePrintError, "godot_print_error", "print_error");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_print_error_with_message, GDExtensionInterfacePrintErrorWithMessage, "godot_print_error_with_message", "print_error_with_message");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_print_warning, GDExtensionInterfacePrintWarning, "godot_print_warning", "print_warning");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_print_warning_with_message, GDExtensionInterfacePrintWarningWithMessage, "godot_print_warning_with_message", "print_warning_with_message");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_print_script_error, GDExtensionInterfacePrintScriptError, "godot_print_script_error", "print_script_error");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_print_script_error_with_message, GDExtensionInterfacePrintScriptErrorWithMessage, "godot_print_script_error_with_message", "print_script_error_with_message");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_get_native_struct_size, GDExtensionInterfaceGetNativeStructSize, "godot_get_native_struct_size", "get_native_struct_size");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_new_copy, GDExtensionInterfaceVariantNewCopy, "godot_variant_new_copy", "variant_new_copy");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_new_nil, GDExtensionInterfaceVariantNewNil, "godot_variant_new_nil", "variant_new_nil");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_destroy, GDExtensionInterfaceVariantDestroy, "godot_variant_destroy", "variant_destroy");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_call, GDExtensionInterfaceVariantCall, "godot_variant_call", "variant_call");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_call_static, GDExtensionInterfaceVariantCallStatic, "godot_variant_call_static", "variant_call_static");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_evaluate, GDExtensionInterfaceVariantEvaluate, "godot_variant_evaluate", "variant_evaluate");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_set, GDExtensionInterfaceVariantSet, "godot_variant_set", "variant_set");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_set_named, GDExtensionInterfaceVariantSetNamed, "godot_variant_set_named", "variant_set_named");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_set_keyed, GDExtensionInterfaceVariantSetKeyed, "godot_variant_set_keyed", "variant_set_keyed");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_set_indexed, GDExtensionInterfaceVariantSetIndexed, "godot_variant_set_indexed", "variant_set_indexed");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get, GDExtensionInterfaceVariantGet, "godot_variant_get", "variant_get");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_named, GDExtensionInterfaceVariantGetNamed, "godot_variant_get_named", "variant_get_named");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_keyed, GDExtensionInterfaceVariantGetKeyed, "godot_variant_get_keyed", "variant_get_keyed");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_indexed, GDExtensionInterfaceVariantGetIndexed, "godot_variant_get_indexed", "variant_get_indexed");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_iter_init, GDExtensionInterfaceVariantIterInit, "godot_variant_iter_init", "variant_iter_init");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_iter_next, GDExtensionInterfaceVariantIterNext, "godot_variant_iter_next", "variant_iter_next");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_iter_get, GDExtensionInterfaceVariantIterGet, "godot_variant_iter_get", "variant_iter_get");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_hash, GDExtensionInterfaceVariantHash, "godot_variant_hash", "variant_hash");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_recursive_hash, GDExtensionInterfaceVariantRecursiveHash, "godot_variant_recursive_hash", "variant_recursive_hash");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_hash_compare, GDExtensionInterfaceVariantHashCompare, "godot_variant_hash_compare", "variant_hash_compare");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_booleanize, GDExtensionInterfaceVariantBooleanize, "godot_variant_booleanize", "variant_booleanize");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_duplicate, GDExtensionInterfaceVariantDuplicate, "godot_variant_duplicate", "variant_duplicate");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_stringify, GDExtensionInterfaceVariantStringify, "godot_variant_stringify", "variant_stringify");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_type, GDExtensionInterfaceVariantGetType, "godot_variant_get_type", "variant_get_type");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_has_method, GDExtensionInterfaceVariantHasMethod, "godot_variant_has_method", "variant_has_method");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_has_member, GDExtensionInterfaceVariantHasMember, "godot_variant_has_member", "variant_has_member");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_has_key, GDExtensionInterfaceVariantHasKey, "godot_variant_has_key", "variant_has_key");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_object_instance_id, GDExtensionInterfaceVariantGetObjectInstanceId, "godot_variant_get_object_instance_id", "variant_get_object_instance_id");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_type_name, GDExtensionInterfaceVariantGetTypeName, "godot_variant_get_type_name", "variant_get_type_name");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_can_convert, GDExtensionInterfaceVariantCanConvert, "godot_variant_can_convert", "variant_can_convert");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_can_convert_strict, GDExtensionInterfaceVariantCanConvertStrict, "godot_variant_can_convert_strict", "variant_can_convert_strict");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_get_variant_from_type_constructor, GDExtensionInterfaceGetVariantFromTypeConstructor, "godot_get_variant_from_type_constructor", "get_variant_from_type_constructor");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_get_variant_to_type_constructor, GDExtensionInterfaceGetVariantToTypeConstructor, "godot_get_variant_to_type_constructor", "get_variant_to_type_constructor");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_ptr_internal_getter, GDExtensionInterfaceGetVariantGetInternalPtrFunc, "godot_variant_get_ptr_internal_getter", "variant_get_ptr_internal_getter");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_ptr_operator_evaluator, GDExtensionInterfaceVariantGetPtrOperatorEvaluator, "godot_variant_get_ptr_operator_evaluator", "variant_get_ptr_operator_evaluator");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_ptr_builtin_method, GDExtensionInterfaceVariantGetPtrBuiltinMethod, "godot_variant_get_ptr_builtin_method", "variant_get_ptr_builtin_method");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_ptr_constructor, GDExtensionInterfaceVariantGetPtrConstructor, "godot_variant_get_ptr_constructor", "variant_get_ptr_constructor");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_ptr_destructor, GDExtensionInterfaceVariantGetPtrDestructor, "godot_variant_get_ptr_destructor", "variant_get_ptr_destructor");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_construct, GDExtensionInterfaceVariantConstruct, "godot_variant_construct", "variant_construct");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_ptr_setter, GDExtensionInterfaceVariantGetPtrSetter, "godot_variant_get_ptr_setter", "variant_get_ptr_setter");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_ptr_getter, GDExtensionInterfaceVariantGetPtrGetter, "godot_variant_get_ptr_getter", "variant_get_ptr_getter");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_ptr_indexed_setter, GDExtensionInterfaceVariantGetPtrIndexedSetter, "godot_variant_get_ptr_indexed_setter", "variant_get_ptr_indexed_setter");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_ptr_indexed_getter, GDExtensionInterfaceVariantGetPtrIndexedGetter, "godot_variant_get_ptr_indexed_getter", "variant_get_ptr_indexed_getter");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_ptr_keyed_setter, GDExtensionInterfaceVariantGetPtrKeyedSetter, "godot_variant_get_ptr_keyed_setter", "variant_get_ptr_keyed_setter");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_ptr_keyed_getter, GDExtensionInterfaceVariantGetPtrKeyedGetter, "godot_variant_get_ptr_keyed_getter", "variant_get_ptr_keyed_getter");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_ptr_keyed_checker, GDExtensionInterfaceVariantGetPtrKeyedChecker, "godot_variant_get_ptr_keyed_checker", "variant_get_ptr_keyed_checker");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_constant_value, GDExtensionInterfaceVariantGetConstantValue, "godot_variant_get_constant_value", "variant_get_constant_value");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_variant_get_ptr_utility_function, GDExtensionInterfaceVariantGetPtrUtilityFunction, "godot_variant_get_ptr_utility_function", "variant_get_ptr_utility_function");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_new_with_latin1_chars, GDExtensionInterfaceStringNewWithLatin1Chars, "godot_string_new_with_latin1_chars", "string_new_with_latin1_chars");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_new_with_utf8_chars, GDExtensionInterfaceStringNewWithUtf8Chars, "godot_string_new_with_utf8_chars", "string_new_with_utf8_chars");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_new_with_utf16_chars, GDExtensionInterfaceStringNewWithUtf16Chars, "godot_string_new_with_utf16_chars", "string_new_with_utf16_chars");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_new_with_utf32_chars, GDExtensionInterfaceStringNewWithUtf32Chars, "godot_string_new_with_utf32_chars", "string_new_with_utf32_chars");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_new_with_wide_chars, GDExtensionInterfaceStringNewWithWideChars, "godot_string_new_with_wide_chars", "string_new_with_wide_chars");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_new_with_latin1_chars_and_len, GDExtensionInterfaceStringNewWithLatin1CharsAndLen, "godot_string_new_with_latin1_chars_and_len", "string_new_with_latin1_chars_and_len");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_new_with_utf8_chars_and_len, GDExtensionInterfaceStringNewWithUtf8CharsAndLen, "godot_string_new_with_utf8_chars_and_len", "string_new_with_utf8_chars_and_len");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_new_with_utf8_chars_and_len2, GDExtensionInterfaceStringNewWithUtf8CharsAndLen2, "godot_string_new_with_utf8_chars_and_len2", "string_new_with_utf8_chars_and_len2");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_new_with_utf16_chars_and_len, GDExtensionInterfaceStringNewWithUtf16CharsAndLen, "godot_string_new_with_utf16_chars_and_len", "string_new_with_utf16_chars_and_len");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_new_with_utf16_chars_and_len2, GDExtensionInterfaceStringNewWithUtf16CharsAndLen2, "godot_string_new_with_utf16_chars_and_len2", "string_new_with_utf16_chars_and_len2");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_new_with_utf32_chars_and_len, GDExtensionInterfaceStringNewWithUtf32CharsAndLen, "godot_string_new_with_utf32_chars_and_len", "string_new_with_utf32_chars_and_len");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_new_with_wide_chars_and_len, GDExtensionInterfaceStringNewWithWideCharsAndLen, "godot_string_new_with_wide_chars_and_len", "string_new_with_wide_chars_and_len");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_to_latin1_chars, GDExtensionInterfaceStringToLatin1Chars, "godot_string_to_latin1_chars", "string_to_latin1_chars");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_to_utf8_chars, GDExtensionInterfaceStringToUtf8Chars, "godot_string_to_utf8_chars", "string_to_utf8_chars");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_to_utf16_chars, GDExtensionInterfaceStringToUtf16Chars, "godot_string_to_utf16_chars", "string_to_utf16_chars");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_to_utf32_chars, GDExtensionInterfaceStringToUtf32Chars, "godot_string_to_utf32_chars", "string_to_utf32_chars");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_to_wide_chars, GDExtensionInterfaceStringToWideChars, "godot_string_to_wide_chars", "string_to_wide_chars");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_operator_index, GDExtensionInterfaceStringOperatorIndex, "godot_string_operator_index", "string_operator_index");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_operator_index_const, GDExtensionInterfaceStringOperatorIndexConst, "godot_string_operator_index_const", "string_operator_index_const");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_operator_plus_eq_string, GDExtensionInterfaceStringOperatorPlusEqString, "godot_string_operator_plus_eq_string", "string_operator_plus_eq_string");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_operator_plus_eq_char, GDExtensionInterfaceStringOperatorPlusEqChar, "godot_string_operator_plus_eq_char", "string_operator_plus_eq_char");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_operator_plus_eq_cstr, GDExtensionInterfaceStringOperatorPlusEqCstr, "godot_string_operator_plus_eq_cstr", "string_operator_plus_eq_cstr");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_operator_plus_eq_wcstr, GDExtensionInterfaceStringOperatorPlusEqWcstr, "godot_string_operator_plus_eq_wcstr", "string_operator_plus_eq_wcstr");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_operator_plus_eq_c32str, GDExtensionInterfaceStringOperatorPlusEqC32str, "godot_string_operator_plus_eq_c32str", "string_operator_plus_eq_c32str");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_resize, GDExtensionInterfaceStringResize, "godot_string_resize", "string_resize");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_name_new_with_latin1_chars, GDExtensionInterfaceStringNameNewWithLatin1Chars, "godot_string_name_new_with_latin1_chars", "string_name_new_with_latin1_chars");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_name_new_with_utf8_chars, GDExtensionInterfaceStringNameNewWithUtf8Chars, "godot_string_name_new_with_utf8_chars", "string_name_new_with_utf8_chars");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_string_name_new_with_utf8_chars_and_len, GDExtensionInterfaceStringNameNewWithUtf8CharsAndLen, "godot_string_name_new_with_utf8_chars_and_len", "string_name_new_with_utf8_chars_and_len");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_xml_parser_open_buffer, GDExtensionInterfaceXmlParserOpenBuffer, "godot_xml_parser_open_buffer", "xml_parser_open_buffer");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_file_access_store_buffer, GDExtensionInterfaceFileAccessStoreBuffer, "godot_file_access_store_buffer", "file_access_store_buffer");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_file_access_get_buffer, GDExtensionInterfaceFileAccessGetBuffer, "godot_file_access_get_buffer", "file_access_get_buffer");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_image_ptrw, GDExtensionInterfaceImagePtrw, "godot_image_ptrw", "image_ptrw");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_image_ptr, GDExtensionInterfaceImagePtr, "godot_image_ptr", "image_ptr");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_worker_thread_pool_add_native_group_task, GDExtensionInterfaceWorkerThreadPoolAddNativeGroupTask, "godot_worker_thread_pool_add_native_group_task", "worker_thread_pool_add_native_group_task");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_worker_thread_pool_add_native_task, GDExtensionInterfaceWorkerThreadPoolAddNativeTask, "godot_worker_thread_pool_add_native_task", "worker_thread_pool_add_native_task");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_byte_array_operator_index, GDExtensionInterfacePackedByteArrayOperatorIndex, "godot_packed_byte_array_operator_index", "packed_byte_array_operator_index");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_byte_array_operator_index_const, GDExtensionInterfacePackedByteArrayOperatorIndexConst, "godot_packed_byte_array_operator_index_const", "packed_byte_array_operator_index_const");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_float32_array_operator_index, GDExtensionInterfacePackedFloat32ArrayOperatorIndex, "godot_packed_float32_array_operator_index", "packed_float32_array_operator_index");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_float32_array_operator_index_const, GDExtensionInterfacePackedFloat32ArrayOperatorIndexConst, "godot_packed_float32_array_operator_index_const", "packed_float32_array_operator_index_const");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_float64_array_operator_index, GDExtensionInterfacePackedFloat64ArrayOperatorIndex, "godot_packed_float64_array_operator_index", "packed_float64_array_operator_index");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_float64_array_operator_index_const, GDExtensionInterfacePackedFloat64ArrayOperatorIndexConst, "godot_packed_float64_array_operator_index_const", "packed_float64_array_operator_index_const");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_int32_array_operator_index, GDExtensionInterfacePackedInt32ArrayOperatorIndex, "godot_packed_int32_array_operator_index", "packed_int32_array_operator_index");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_int32_array_operator_index_const, GDExtensionInterfacePackedInt32ArrayOperatorIndexConst, "godot_packed_int32_array_operator_index_const", "packed_int32_array_operator_index_const");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_int64_array_operator_index, GDExtensionInterfacePackedInt64ArrayOperatorIndex, "godot_packed_int64_array_operator_index", "packed_int64_array_operator_index");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_int64_array_operator_index_const, GDExtensionInterfacePackedInt64ArrayOperatorIndexConst, "godot_packed_int64_array_operator_index_const", "packed_int64_array_operator_index_const");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_string_array_operator_index, GDExtensionInterfacePackedStringArrayOperatorIndex, "godot_packed_string_array_operator_index", "packed_string_array_operator_index");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_string_array_operator_index_const, GDExtensionInterfacePackedStringArrayOperatorIndexConst, "godot_packed_string_array_operator_index_const", "packed_string_array_operator_index_const");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_vector2_array_operator_index, GDExtensionInterfacePackedVector2ArrayOperatorIndex, "godot_packed_vector2_array_operator_index", "packed_vector2_array_operator_index");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_vector2_array_operator_index_const, GDExtensionInterfacePackedVector2ArrayOperatorIndexConst, "godot_packed_vector2_array_operator_index_const", "packed_vector2_array_operator_index_const");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_vector3_array_operator_index, GDExtensionInterfacePackedVector3ArrayOperatorIndex, "godot_packed_vector3_array_operator_index", "packed_vector3_array_operator_index");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_vector3_array_operator_index_const, GDExtensionInterfacePackedVector3ArrayOperatorIndexConst, "godot_packed_vector3_array_operator_index_const", "packed_vector3_array_operator_index_const");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_vector4_array_operator_index, GDExtensionInterfacePackedVector4ArrayOperatorIndex, "godot_packed_vector4_array_operator_index", "packed_vector4_array_operator_index");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_vector4_array_operator_index_const, GDExtensionInterfacePackedVector4ArrayOperatorIndexConst, "godot_packed_vector4_array_operator_index_const", "packed_vector4_array_operator_index_const");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_color_array_operator_index, GDExtensionInterfacePackedColorArrayOperatorIndex, "godot_packed_color_array_operator_index", "packed_color_array_operator_index");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_packed_color_array_operator_index_const, GDExtensionInterfacePackedColorArrayOperatorIndexConst, "godot_packed_color_array_operator_index_const", "packed_color_array_operator_index_const");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_array_operator_index, GDExtensionInterfaceArrayOperatorIndex, "godot_array_operator_index", "array_operator_index");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_array_operator_index_const, GDExtensionInterfaceArrayOperatorIndexConst, "godot_array_operator_index_const", "array_operator_index_const");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_array_ref, GDExtensionInterfaceArrayRef, "godot_array_ref", "array_ref");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_array_set_typed, GDExtensionInterfaceArraySetTyped, "godot_array_set_typed", "array_set_typed");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_dictionary_operator_index, GDExtensionInterfaceDictionaryOperatorIndex, "godot_dictionary_operator_index", "dictionary_operator_index");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_dictionary_operator_index_const, GDExtensionInterfaceDictionaryOperatorIndexConst, "godot_dictionary_operator_index_const", "dictionary_operator_index_const");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_dictionary_set_typed, GDExtensionInterfaceDictionarySetTyped, "godot_dictionary_set_typed", "dictionary_set_typed");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_method_bind_call, GDExtensionInterfaceObjectMethodBindCall, "godot_object_method_bind_call", "object_method_bind_call");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_method_bind_ptrcall, GDExtensionInterfaceObjectMethodBindPtrcall, "godot_object_method_bind_ptrcall", "object_method_bind_ptrcall");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_destroy, GDExtensionInterfaceObjectDestroy, "godot_object_destroy", "object_destroy");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_global_get_singleton, GDExtensionInterfaceGlobalGetSingleton, "godot_global_get_singleton", "global_get_singleton");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_get_instance_binding, GDExtensionInterfaceObjectGetInstanceBinding, "godot_object_get_instance_binding", "object_get_instance_binding");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_set_instance_binding, GDExtensionInterfaceObjectSetInstanceBinding, "godot_object_set_instance_binding", "object_set_instance_binding");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_free_instance_binding, GDExtensionInterfaceObjectFreeInstanceBinding, "godot_object_free_instance_binding", "object_free_instance_binding");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_set_instance, GDExtensionInterfaceObjectSetInstance, "godot_object_set_instance", "object_set_instance");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_get_class_name, GDExtensionInterfaceObjectGetClassName, "godot_object_get_class_name", "object_get_class_name");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_cast_to, GDExtensionInterfaceObjectCastTo, "godot_object_cast_to", "object_cast_to");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_get_instance_from_id, GDExtensionInterfaceObjectGetInstanceFromId, "godot_object_get_instance_from_id", "object_get_instance_from_id");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_get_instance_id, GDExtensionInterfaceObjectGetInstanceId, "godot_object_get_instance_id", "object_get_instance_id");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_has_script_method, GDExtensionInterfaceObjectHasScriptMethod, "godot_object_has_script_method", "object_has_script_method");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_call_script_method, GDExtensionInterfaceObjectCallScriptMethod, "godot_object_call_script_method", "object_call_script_method");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_ref_get_object, GDExtensionInterfaceRefGetObject, "godot_ref_get_object", "ref_get_object");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_ref_set_object, GDExtensionInterfaceRefSetObject, "godot_ref_set_object", "ref_set_object");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_script_instance_create, GDExtensionInterfaceScriptInstanceCreate, "godot_script_instance_create", "script_instance_create");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_script_instance_create2, GDExtensionInterfaceScriptInstanceCreate2, "godot_script_instance_create2", "script_instance_create2");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_script_instance_create3, GDExtensionInterfaceScriptInstanceCreate3, "godot_script_instance_create3", "script_instance_create3");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_placeholder_script_instance_create, GDExtensionInterfacePlaceHolderScriptInstanceCreate, "godot_placeholder_script_instance_create", "placeholder_script_instance_create");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_placeholder_script_instance_update, GDExtensionInterfacePlaceHolderScriptInstanceUpdate, "godot_placeholder_script_instance_update", "placeholder_script_instance_update");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_get_script_instance, GDExtensionInterfaceObjectGetScriptInstance, "godot_object_get_script_instance", "object_get_script_instance");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_object_set_script_instance, GDExtensionInterfaceObjectSetScriptInstance, "godot_object_set_script_instance", "object_set_script_instance");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_callable_custom_create, GDExtensionInterfaceCallableCustomCreate, "godot_callable_custom_create", "callable_custom_create");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_callable_custom_create2, GDExtensionInterfaceCallableCustomCreate2, "godot_callable_custom_create2", "callable_custom_create2");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_callable_custom_get_userdata, GDExtensionInterfaceCallableCustomGetUserData, "godot_callable_custom_get_userdata", "callable_custom_get_userdata");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_construct_object, GDExtensionInterfaceClassdbConstructObject, "godot_classdb_construct_object", "classdb_construct_object");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_construct_object2, GDExtensionInterfaceClassdbConstructObject2, "godot_classdb_construct_object2", "classdb_construct_object2");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_get_method_bind, GDExtensionInterfaceClassdbGetMethodBind, "godot_classdb_get_method_bind", "classdb_get_method_bind");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_get_class_tag, GDExtensionInterfaceClassdbGetClassTag, "godot_classdb_get_class_tag", "classdb_get_class_tag");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_register_extension_class, GDExtensionInterfaceClassdbRegisterExtensionClass, "godot_classdb_register_extension_class", "classdb_register_extension_class");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_register_extension_class2, GDExtensionInterfaceClassdbRegisterExtensionClass2, "godot_classdb_register_extension_class2", "classdb_register_extension_class2");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_register_extension_class3, GDExtensionInterfaceClassdbRegisterExtensionClass3, "godot_classdb_register_extension_class3", "classdb_register_extension_class3");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_register_extension_class4, GDExtensionInterfaceClassdbRegisterExtensionClass4, "godot_classdb_register_extension_class4", "classdb_register_extension_class4");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_register_extension_class5, GDExtensionInterfaceClassdbRegisterExtensionClass5, "godot_classdb_register_extension_class5", "classdb_register_extension_class5");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_register_extension_class_method, GDExtensionInterfaceClassdbRegisterExtensionClassMethod, "godot_classdb_register_extension_class_method", "classdb_register_extension_class_method");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_register_extension_class_virtual_method, GDExtensionInterfaceClassdbRegisterExtensionClassVirtualMethod, "godot_classdb_register_extension_class_virtual_method", "classdb_register_extension_class_virtual_method");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_register_extension_class_integer_constant, GDExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant, "godot_classdb_register_extension_class_integer_constant", "classdb_register_extension_class_integer_constant");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_register_extension_class_property, GDExtensionInterfaceClassdbRegisterExtensionClassProperty, "godot_classdb_register_extension_class_property", "classdb_register_extension_class_property");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_register_extension_class_property_indexed, GDExtensionInterfaceClassdbRegisterExtensionClassPropertyIndexed, "godot_classdb_register_extension_class_property_indexed", "classdb_register_extension_class_property_indexed");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_register_extension_class_property_group, GDExtensionInterfaceClassdbRegisterExtensionClassPropertyGroup, "godot_classdb_register_extension_class_property_group", "classdb_register_extension_class_property_group");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_register_extension_class_property_subgroup, GDExtensionInterfaceClassdbRegisterExtensionClassPropertySubgroup, "godot_classdb_register_extension_class_property_subgroup", "classdb_register_extension_class_property_subgroup");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_register_extension_class_signal, GDExtensionInterfaceClassdbRegisterExtensionClassSignal, "godot_classdb_register_extension_class_signal", "classdb_register_extension_class_signal");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_classdb_unregister_extension_class, GDExtensionInterfaceClassdbUnregisterExtensionClass, "godot_classdb_unregister_extension_class", "classdb_unregister_extension_class");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_get_library_path, GDExtensionInterfaceGetLibraryPath, "godot_get_library_path", "get_library_path");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_editor_add_plugin, GDExtensionInterfaceEditorAddPlugin, "godot_editor_add_plugin", "editor_add_plugin");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_editor_remove_plugin, GDExtensionInterfaceEditorRemovePlugin, "godot_editor_remove_plugin", "editor_remove_plugin");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_editor_help_load_xml_from_utf8_chars, GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8Chars, "godot_editor_help_load_xml_from_utf8_chars", "editor_help_load_xml_from_utf8_chars");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_editor_help_load_xml_from_utf8_chars_and_len, GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8CharsAndLen, "godot_editor_help_load_xml_from_utf8_chars_and_len", "editor_help_load_xml_from_utf8_chars_and_len");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_editor_register_get_classes_used_callback, GDExtensionInterfaceEditorRegisterGetClassesUsedCallback, "godot_editor_register_get_classes_used_callback", "editor_register_get_classes_used_callback");
    GDCC_RESOLVE_INTERFACE(gdcc_interface_register_main_loop_callbacks, GDExtensionInterfaceRegisterMainLoopCallbacks, "godot_register_main_loop_callbacks", "register_main_loop_callbacks");
    return true;

gdcc_initialize_interface_failed:
    gdcc_clear_interface_pointers();
    return false;
}

#undef GDCC_RESOLVE_INTERFACE

