/* This file was generated by GodotBindingTool. */
/* Do not edit by hand. */
#ifndef GDCC_GODOT_BUILTIN_LAYOUT_H
#define GDCC_GODOT_BUILTIN_LAYOUT_H

#include <godot_builtin_sizes.h>

#ifdef GDCC_GODOT_BUILD_FLOAT_64
#define GDCC_GODOT_OFFSET_Vector2_x 0
#define GDCC_GODOT_META_Vector2_x float
#define GDCC_GODOT_OFFSET_Vector2_y 4
#define GDCC_GODOT_META_Vector2_y float
#define GDCC_GODOT_OFFSET_Vector2i_x 0
#define GDCC_GODOT_META_Vector2i_x int32_t
#define GDCC_GODOT_OFFSET_Vector2i_y 4
#define GDCC_GODOT_META_Vector2i_y int32_t
#define GDCC_GODOT_OFFSET_Rect2_position 0
#define GDCC_GODOT_META_Rect2_position godot_Vector2
#define GDCC_GODOT_OFFSET_Rect2_size 8
#define GDCC_GODOT_META_Rect2_size godot_Vector2
#define GDCC_GODOT_OFFSET_Rect2i_position 0
#define GDCC_GODOT_META_Rect2i_position godot_Vector2i
#define GDCC_GODOT_OFFSET_Rect2i_size 8
#define GDCC_GODOT_META_Rect2i_size godot_Vector2i
#define GDCC_GODOT_OFFSET_Vector3_x 0
#define GDCC_GODOT_META_Vector3_x float
#define GDCC_GODOT_OFFSET_Vector3_y 4
#define GDCC_GODOT_META_Vector3_y float
#define GDCC_GODOT_OFFSET_Vector3_z 8
#define GDCC_GODOT_META_Vector3_z float
#define GDCC_GODOT_OFFSET_Vector3i_x 0
#define GDCC_GODOT_META_Vector3i_x int32_t
#define GDCC_GODOT_OFFSET_Vector3i_y 4
#define GDCC_GODOT_META_Vector3i_y int32_t
#define GDCC_GODOT_OFFSET_Vector3i_z 8
#define GDCC_GODOT_META_Vector3i_z int32_t
#define GDCC_GODOT_OFFSET_Transform2D_x 0
#define GDCC_GODOT_META_Transform2D_x godot_Vector2
#define GDCC_GODOT_OFFSET_Transform2D_y 8
#define GDCC_GODOT_META_Transform2D_y godot_Vector2
#define GDCC_GODOT_OFFSET_Transform2D_origin 16
#define GDCC_GODOT_META_Transform2D_origin godot_Vector2
#define GDCC_GODOT_OFFSET_Vector4_x 0
#define GDCC_GODOT_META_Vector4_x float
#define GDCC_GODOT_OFFSET_Vector4_y 4
#define GDCC_GODOT_META_Vector4_y float
#define GDCC_GODOT_OFFSET_Vector4_z 8
#define GDCC_GODOT_META_Vector4_z float
#define GDCC_GODOT_OFFSET_Vector4_w 12
#define GDCC_GODOT_META_Vector4_w float
#define GDCC_GODOT_OFFSET_Vector4i_x 0
#define GDCC_GODOT_META_Vector4i_x int32_t
#define GDCC_GODOT_OFFSET_Vector4i_y 4
#define GDCC_GODOT_META_Vector4i_y int32_t
#define GDCC_GODOT_OFFSET_Vector4i_z 8
#define GDCC_GODOT_META_Vector4i_z int32_t
#define GDCC_GODOT_OFFSET_Vector4i_w 12
#define GDCC_GODOT_META_Vector4i_w int32_t
#define GDCC_GODOT_OFFSET_Plane_normal 0
#define GDCC_GODOT_META_Plane_normal godot_Vector3
#define GDCC_GODOT_OFFSET_Plane_d 12
#define GDCC_GODOT_META_Plane_d float
#define GDCC_GODOT_OFFSET_Quaternion_x 0
#define GDCC_GODOT_META_Quaternion_x float
#define GDCC_GODOT_OFFSET_Quaternion_y 4
#define GDCC_GODOT_META_Quaternion_y float
#define GDCC_GODOT_OFFSET_Quaternion_z 8
#define GDCC_GODOT_META_Quaternion_z float
#define GDCC_GODOT_OFFSET_Quaternion_w 12
#define GDCC_GODOT_META_Quaternion_w float
#define GDCC_GODOT_OFFSET_AABB_position 0
#define GDCC_GODOT_META_AABB_position godot_Vector3
#define GDCC_GODOT_OFFSET_AABB_size 12
#define GDCC_GODOT_META_AABB_size godot_Vector3
#define GDCC_GODOT_OFFSET_Basis_x 0
#define GDCC_GODOT_META_Basis_x godot_Vector3
#define GDCC_GODOT_OFFSET_Basis_y 12
#define GDCC_GODOT_META_Basis_y godot_Vector3
#define GDCC_GODOT_OFFSET_Basis_z 24
#define GDCC_GODOT_META_Basis_z godot_Vector3
#define GDCC_GODOT_OFFSET_Transform3D_basis 0
#define GDCC_GODOT_META_Transform3D_basis godot_Basis
#define GDCC_GODOT_OFFSET_Transform3D_origin 36
#define GDCC_GODOT_META_Transform3D_origin godot_Vector3
#define GDCC_GODOT_OFFSET_Projection_x 0
#define GDCC_GODOT_META_Projection_x godot_Vector4
#define GDCC_GODOT_OFFSET_Projection_y 16
#define GDCC_GODOT_META_Projection_y godot_Vector4
#define GDCC_GODOT_OFFSET_Projection_z 32
#define GDCC_GODOT_META_Projection_z godot_Vector4
#define GDCC_GODOT_OFFSET_Projection_w 48
#define GDCC_GODOT_META_Projection_w godot_Vector4
#define GDCC_GODOT_OFFSET_Color_r 0
#define GDCC_GODOT_META_Color_r float
#define GDCC_GODOT_OFFSET_Color_g 4
#define GDCC_GODOT_META_Color_g float
#define GDCC_GODOT_OFFSET_Color_b 8
#define GDCC_GODOT_META_Color_b float
#define GDCC_GODOT_OFFSET_Color_a 12
#define GDCC_GODOT_META_Color_a float
#endif

#endif
