/* This file was generated by GodotBindingTool. */
/* Do not edit by hand. */
#ifndef GDCC_GODOT_GLOBAL_CONSTANTS_H
#define GDCC_GODOT_GLOBAL_CONSTANTS_H

/* Godot 4.5.1 exports no standalone global constants. */

#endif
