/* This file was generated by GodotInterfaceGenerator. */
/* Do not edit by hand. */
#ifndef GDCC_GODOT_BINDING_H
#define GDCC_GODOT_BINDING_H

#include <godot_abi.h>
#include <godot_interface.h>

#endif
