/* This file was generated by GodotBindingTool. */
/* Do not edit by hand. */
#ifndef GDCC_GODOT_UTILITY_H
#define GDCC_GODOT_UTILITY_H

#include <godot_builtin.h>

#ifdef __cplusplus
extern "C" {
#endif

GDCC_GODOT_DECL godot_float godot_sin(godot_float angle_rad);
GDCC_GODOT_DECL godot_float godot_cos(godot_float angle_rad);
GDCC_GODOT_DECL godot_float godot_tan(godot_float angle_rad);
GDCC_GODOT_DECL godot_float godot_sinh(godot_float x);
GDCC_GODOT_DECL godot_float godot_cosh(godot_float x);
GDCC_GODOT_DECL godot_float godot_tanh(godot_float x);
GDCC_GODOT_DECL godot_float godot_asin(godot_float x);
GDCC_GODOT_DECL godot_float godot_acos(godot_float x);
GDCC_GODOT_DECL godot_float godot_atan(godot_float x);
GDCC_GODOT_DECL godot_float godot_atan2(godot_float y, godot_float x);
GDCC_GODOT_DECL godot_float godot_asinh(godot_float x);
GDCC_GODOT_DECL godot_float godot_acosh(godot_float x);
GDCC_GODOT_DECL godot_float godot_atanh(godot_float x);
GDCC_GODOT_DECL godot_float godot_sqrt(godot_float x);
GDCC_GODOT_DECL godot_float godot_fmod(godot_float x, godot_float y);
GDCC_GODOT_DECL godot_float godot_fposmod(godot_float x, godot_float y);
GDCC_GODOT_DECL godot_int godot_posmod(godot_int x, godot_int y);
GDCC_GODOT_DECL godot_Variant godot_floor(const godot_Variant * x);
GDCC_GODOT_DECL godot_float godot_floorf(godot_float x);
GDCC_GODOT_DECL godot_int godot_floori(godot_float x);
GDCC_GODOT_DECL godot_Variant godot_ceil(const godot_Variant * x);
GDCC_GODOT_DECL godot_float godot_ceilf(godot_float x);
GDCC_GODOT_DECL godot_int godot_ceili(godot_float x);
GDCC_GODOT_DECL godot_Variant godot_round(const godot_Variant * x);
GDCC_GODOT_DECL godot_float godot_roundf(godot_float x);
GDCC_GODOT_DECL godot_int godot_roundi(godot_float x);
GDCC_GODOT_DECL godot_Variant godot_abs(const godot_Variant * x);
GDCC_GODOT_DECL godot_float godot_absf(godot_float x);
GDCC_GODOT_DECL godot_int godot_absi(godot_int x);
GDCC_GODOT_DECL godot_Variant godot_sign(const godot_Variant * x);
GDCC_GODOT_DECL godot_float godot_signf(godot_float x);
GDCC_GODOT_DECL godot_int godot_signi(godot_int x);
GDCC_GODOT_DECL godot_Variant godot_snapped(const godot_Variant * x, const godot_Variant * step);
GDCC_GODOT_DECL godot_float godot_snappedf(godot_float x, godot_float step);
GDCC_GODOT_DECL godot_int godot_snappedi(godot_float x, godot_int step);
GDCC_GODOT_DECL godot_float godot_pow(godot_float base, godot_float exp);
GDCC_GODOT_DECL godot_float godot_log(godot_float x);
GDCC_GODOT_DECL godot_float godot_exp(godot_float x);
GDCC_GODOT_DECL godot_bool godot_is_nan(godot_float x);
GDCC_GODOT_DECL godot_bool godot_is_inf(godot_float x);
GDCC_GODOT_DECL godot_bool godot_is_equal_approx(godot_float a, godot_float b);
GDCC_GODOT_DECL godot_bool godot_is_zero_approx(godot_float x);
GDCC_GODOT_DECL godot_bool godot_is_finite(godot_float x);
GDCC_GODOT_DECL godot_float godot_ease(godot_float x, godot_float curve);
GDCC_GODOT_DECL godot_int godot_step_decimals(godot_float x);
GDCC_GODOT_DECL godot_Variant godot_lerp(const godot_Variant * from, const godot_Variant * to, const godot_Variant * weight);
GDCC_GODOT_DECL godot_float godot_lerpf(godot_float from, godot_float to, godot_float weight);
GDCC_GODOT_DECL godot_float godot_cubic_interpolate(godot_float from, godot_float to, godot_float pre, godot_float post, godot_float weight);
GDCC_GODOT_DECL godot_float godot_cubic_interpolate_angle(godot_float from, godot_float to, godot_float pre, godot_float post, godot_float weight);
GDCC_GODOT_DECL godot_float godot_cubic_interpolate_in_time(godot_float from, godot_float to, godot_float pre, godot_float post, godot_float weight, godot_float to_t, godot_float pre_t, godot_float post_t);
GDCC_GODOT_DECL godot_float godot_cubic_interpolate_angle_in_time(godot_float from, godot_float to, godot_float pre, godot_float post, godot_float weight, godot_float to_t, godot_float pre_t, godot_float post_t);
GDCC_GODOT_DECL godot_float godot_bezier_interpolate(godot_float start, godot_float control_1, godot_float control_2, godot_float end, godot_float t);
GDCC_GODOT_DECL godot_float godot_bezier_derivative(godot_float start, godot_float control_1, godot_float control_2, godot_float end, godot_float t);
GDCC_GODOT_DECL godot_float godot_angle_difference(godot_float from, godot_float to);
GDCC_GODOT_DECL godot_float godot_lerp_angle(godot_float from, godot_float to, godot_float weight);
GDCC_GODOT_DECL godot_float godot_inverse_lerp(godot_float from, godot_float to, godot_float weight);
GDCC_GODOT_DECL godot_float godot_remap(godot_float value, godot_float istart, godot_float istop, godot_float ostart, godot_float ostop);
GDCC_GODOT_DECL godot_float godot_smoothstep(godot_float from, godot_float to, godot_float x);
GDCC_GODOT_DECL godot_float godot_move_toward(godot_float from, godot_float to, godot_float delta);
GDCC_GODOT_DECL godot_float godot_rotate_toward(godot_float from, godot_float to, godot_float delta);
GDCC_GODOT_DECL godot_float godot_deg_to_rad(godot_float deg);
GDCC_GODOT_DECL godot_float godot_rad_to_deg(godot_float rad);
GDCC_GODOT_DECL godot_float godot_linear_to_db(godot_float lin);
GDCC_GODOT_DECL godot_float godot_db_to_linear(godot_float db);
GDCC_GODOT_DECL godot_Variant godot_wrap(const godot_Variant * value, const godot_Variant * min, const godot_Variant * max);
GDCC_GODOT_DECL godot_int godot_wrapi(godot_int value, godot_int min, godot_int max);
GDCC_GODOT_DECL godot_float godot_wrapf(godot_float value, godot_float min, godot_float max);
GDCC_GODOT_DECL godot_Variant godot_max(const godot_Variant * arg1, const godot_Variant * arg2, const godot_Variant **argv, godot_int argc);
GDCC_GODOT_DECL godot_int godot_maxi(godot_int a, godot_int b);
GDCC_GODOT_DECL godot_float godot_maxf(godot_float a, godot_float b);
GDCC_GODOT_DECL godot_Variant godot_min(const godot_Variant * arg1, const godot_Variant * arg2, const godot_Variant **argv, godot_int argc);
GDCC_GODOT_DECL godot_int godot_mini(godot_int a, godot_int b);
GDCC_GODOT_DECL godot_float godot_minf(godot_float a, godot_float b);
GDCC_GODOT_DECL godot_Variant godot_clamp(const godot_Variant * value, const godot_Variant * min, const godot_Variant * max);
GDCC_GODOT_DECL godot_int godot_clampi(godot_int value, godot_int min, godot_int max);
GDCC_GODOT_DECL godot_float godot_clampf(godot_float value, godot_float min, godot_float max);
GDCC_GODOT_DECL godot_int godot_nearest_po2(godot_int value);
GDCC_GODOT_DECL godot_float godot_pingpong(godot_float value, godot_float length);
GDCC_GODOT_DECL void godot_randomize(void);
GDCC_GODOT_DECL godot_int godot_randi(void);
GDCC_GODOT_DECL godot_float godot_randf(void);
GDCC_GODOT_DECL godot_int godot_randi_range(godot_int from, godot_int to);
GDCC_GODOT_DECL godot_float godot_randf_range(godot_float from, godot_float to);
GDCC_GODOT_DECL godot_float godot_randfn(godot_float mean, godot_float deviation);
GDCC_GODOT_DECL void godot_seed(godot_int base);
GDCC_GODOT_DECL godot_PackedInt64Array godot_rand_from_seed(godot_int seed);
GDCC_GODOT_DECL godot_Variant godot_weakref(const godot_Variant * obj);
GDCC_GODOT_DECL godot_int godot_typeof(const godot_Variant * variable);
GDCC_GODOT_DECL godot_Variant godot_type_convert(const godot_Variant * variant, godot_int type);
GDCC_GODOT_DECL godot_String godot_str(const godot_Variant * arg1, const godot_Variant **argv, godot_int argc);
GDCC_GODOT_DECL godot_String godot_error_string(godot_int error);
GDCC_GODOT_DECL godot_String godot_type_string(godot_int type);
GDCC_GODOT_DECL void godot_print(const godot_Variant * arg1, const godot_Variant **argv, godot_int argc);
GDCC_GODOT_DECL void godot_print_rich(const godot_Variant * arg1, const godot_Variant **argv, godot_int argc);
GDCC_GODOT_DECL void godot_printerr(const godot_Variant * arg1, const godot_Variant **argv, godot_int argc);
GDCC_GODOT_DECL void godot_printt(const godot_Variant * arg1, const godot_Variant **argv, godot_int argc);
GDCC_GODOT_DECL void godot_prints(const godot_Variant * arg1, const godot_Variant **argv, godot_int argc);
GDCC_GODOT_DECL void godot_printraw(const godot_Variant * arg1, const godot_Variant **argv, godot_int argc);
GDCC_GODOT_DECL void godot_print_verbose(const godot_Variant * arg1, const godot_Variant **argv, godot_int argc);
GDCC_GODOT_DECL void godot_push_error(const godot_Variant * arg1, const godot_Variant **argv, godot_int argc);
GDCC_GODOT_DECL void godot_push_warning(const godot_Variant * arg1, const godot_Variant **argv, godot_int argc);
GDCC_GODOT_DECL godot_String godot_var_to_str(const godot_Variant * variable);
GDCC_GODOT_DECL godot_Variant godot_str_to_var(const godot_String * string);
GDCC_GODOT_DECL godot_PackedByteArray godot_var_to_bytes(const godot_Variant * variable);
GDCC_GODOT_DECL godot_Variant godot_bytes_to_var(const godot_PackedByteArray * bytes);
GDCC_GODOT_DECL godot_PackedByteArray godot_var_to_bytes_with_objects(const godot_Variant * variable);
GDCC_GODOT_DECL godot_Variant godot_bytes_to_var_with_objects(const godot_PackedByteArray * bytes);
GDCC_GODOT_DECL godot_int godot_hash(const godot_Variant * variable);
GDCC_GODOT_DECL godot_Object * godot_instance_from_id(godot_int instance_id);
GDCC_GODOT_DECL godot_bool godot_is_instance_id_valid(godot_int id);
GDCC_GODOT_DECL godot_bool godot_is_instance_valid(const godot_Variant * instance);
GDCC_GODOT_DECL godot_int godot_rid_allocate_id(void);
GDCC_GODOT_DECL godot_RID godot_rid_from_int64(godot_int base);
GDCC_GODOT_DECL godot_bool godot_is_same(const godot_Variant * a, const godot_Variant * b);

#ifdef __cplusplus
}
#endif

#endif
