/* This file was generated by GodotBindingTool. */
/* Do not edit by hand. */
#ifndef GDCC_GODOT_BUILTIN_TYPES_H
#define GDCC_GODOT_BUILTIN_TYPES_H

#include <gdextension/gdextension_interface.h>
#include <godot_macros.h>
#include <godot_builtin_sizes.h>
#include <godot_builtin_layout.h>
#include <math.h>
#include <stdint.h>

#ifdef __cplusplus
typedef bool godot_bool;
#else
typedef GDExtensionBool godot_bool;
#endif
typedef GDExtensionInt godot_int;
typedef double godot_float;
typedef float godot_real_t;
#define godot_inf INFINITY

typedef struct godot_String { uint8_t _[GDCC_GODOT_SIZE_String]; } godot_String;
typedef struct godot_StringName { uint8_t _[GDCC_GODOT_SIZE_StringName]; } godot_StringName;
typedef struct godot_NodePath { uint8_t _[GDCC_GODOT_SIZE_NodePath]; } godot_NodePath;
typedef struct godot_RID { uint8_t _[GDCC_GODOT_SIZE_RID]; } godot_RID;
typedef struct godot_Callable { uint8_t _[GDCC_GODOT_SIZE_Callable]; } godot_Callable;
typedef struct godot_Signal { uint8_t _[GDCC_GODOT_SIZE_Signal]; } godot_Signal;
typedef struct godot_Dictionary { uint8_t _[GDCC_GODOT_SIZE_Dictionary]; } godot_Dictionary;
typedef struct godot_Array { uint8_t _[GDCC_GODOT_SIZE_Array]; } godot_Array;
typedef struct godot_PackedByteArray { uint8_t _[GDCC_GODOT_SIZE_PackedByteArray]; } godot_PackedByteArray;
typedef struct godot_PackedInt32Array { uint8_t _[GDCC_GODOT_SIZE_PackedInt32Array]; } godot_PackedInt32Array;
typedef struct godot_PackedInt64Array { uint8_t _[GDCC_GODOT_SIZE_PackedInt64Array]; } godot_PackedInt64Array;
typedef struct godot_PackedFloat32Array { uint8_t _[GDCC_GODOT_SIZE_PackedFloat32Array]; } godot_PackedFloat32Array;
typedef struct godot_PackedFloat64Array { uint8_t _[GDCC_GODOT_SIZE_PackedFloat64Array]; } godot_PackedFloat64Array;
typedef struct godot_PackedStringArray { uint8_t _[GDCC_GODOT_SIZE_PackedStringArray]; } godot_PackedStringArray;
typedef struct godot_PackedVector2Array { uint8_t _[GDCC_GODOT_SIZE_PackedVector2Array]; } godot_PackedVector2Array;
typedef struct godot_PackedVector3Array { uint8_t _[GDCC_GODOT_SIZE_PackedVector3Array]; } godot_PackedVector3Array;
typedef struct godot_PackedColorArray { uint8_t _[GDCC_GODOT_SIZE_PackedColorArray]; } godot_PackedColorArray;
typedef struct godot_PackedVector4Array { uint8_t _[GDCC_GODOT_SIZE_PackedVector4Array]; } godot_PackedVector4Array;
typedef struct godot_Variant { uint8_t _[GDCC_GODOT_SIZE_Variant]; } godot_Variant;
typedef struct godot_Object godot_Object;

typedef struct godot_Vector2 {
    union {
        godot_real_t coord[2];
        struct { godot_real_t x, y; };
        struct { godot_real_t r, g; };
        struct { godot_real_t s, t; };
        struct { godot_real_t u, v; };
        struct { godot_real_t width, height; };
    };
} godot_Vector2;

typedef struct godot_Vector2i {
    union {
        int32_t coord[2];
        struct { int32_t x, y; };
        struct { int32_t width, height; };
    };
} godot_Vector2i;

typedef struct godot_Rect2 {
    union {
        struct { godot_real_t x, y, width, height; };
        struct { godot_Vector2 position, size; };
    };
} godot_Rect2;

typedef struct godot_Rect2i {
    union {
        struct { int32_t x, y, width, height; };
        struct { godot_Vector2i position, size; };
    };
} godot_Rect2i;

typedef struct godot_Vector3 {
    union {
        godot_real_t coord[3];
        struct { godot_real_t x, y, z; };
        struct { godot_Vector2 xy; godot_real_t _0; };
        struct { godot_real_t _1; godot_Vector2 yz; };
        struct { godot_real_t r, g, b; };
        struct { godot_Vector2 rg; godot_real_t _2; };
        struct { godot_real_t _3; godot_Vector2 gb; };
        struct { godot_real_t s, t, p; };
        struct { godot_Vector2 st; godot_real_t _4; };
        struct { godot_real_t _5; godot_Vector2 tp; };
        struct { godot_real_t width, height, depth; };
    };
} godot_Vector3;

typedef struct godot_Vector3i {
    union {
        int32_t coord[3];
        struct { int32_t x, y, z; };
        struct { godot_Vector2i xy; int32_t _0; };
        struct { int32_t _1; godot_Vector2i yz; };
        struct { int32_t width, height, depth; };
    };
} godot_Vector3i;

typedef struct godot_Transform2D {
    union {
        godot_Vector2 columns[3];
        struct { godot_Vector2 x, y, origin; };
    };
} godot_Transform2D;

typedef struct godot_Vector4 {
    union {
        godot_real_t coord[4];
        struct { godot_real_t x, y, z, w; };
        struct { godot_Vector2 xy, zw; };
        struct { godot_Vector3 xyz; godot_real_t _0; };
        struct { godot_real_t _1; godot_Vector3 yzw; };
        struct { godot_real_t r, g, b, a; };
        struct { godot_Vector2 rg, ba; };
        struct { godot_Vector3 rgb; godot_real_t _2; };
        struct { godot_real_t _3; godot_Vector3 gba; };
    };
} godot_Vector4;

typedef struct godot_Vector4i {
    union {
        int32_t coord[4];
        struct { int32_t x, y, z, w; };
        struct { godot_Vector2i xy, zw; };
        struct { godot_Vector3i xyz; int32_t _0; };
        struct { int32_t _1; godot_Vector3i yzw; };
    };
} godot_Vector4i;

typedef struct godot_Plane {
    union {
        godot_real_t elements[4];
        struct { godot_Vector3 normal; godot_real_t d; };
    };
} godot_Plane;

typedef struct godot_Quaternion {
    union {
        godot_real_t elements[4];
        struct { godot_real_t x, y, z, w; };
        struct { godot_Vector2 xy, zw; };
        struct { godot_Vector3 xyz; godot_real_t _0; };
        struct { godot_real_t _1; godot_Vector3 yzw; };
    };
} godot_Quaternion;

typedef struct godot_AABB {
    godot_Vector3 position;
    godot_Vector3 size;
} godot_AABB;

typedef struct godot_Basis {
    union {
        godot_Vector3 rows[3];
        struct { godot_Vector3 x, y, z; };
    };
} godot_Basis;

typedef struct godot_Transform3D {
    godot_Basis basis;
    godot_Vector3 origin;
} godot_Transform3D;

typedef struct godot_Projection {
    union {
        godot_real_t columns[4][4];
        struct { godot_Vector4 x, y, z, w; };
    };
} godot_Projection;

typedef struct godot_Color {
    union {
        float components[4];
        struct { float r, g, b, a; };
    };
} godot_Color;

GDCC_GODOT_ASSERT_SIZE(bool);
GDCC_GODOT_ASSERT_SIZE(int);
GDCC_GODOT_ASSERT_SIZE(float);
GDCC_GODOT_ASSERT_SIZE(String);
GDCC_GODOT_ASSERT_SIZE(Vector2);
GDCC_GODOT_ASSERT_SIZE(Vector2i);
GDCC_GODOT_ASSERT_SIZE(Rect2);
GDCC_GODOT_ASSERT_SIZE(Rect2i);
GDCC_GODOT_ASSERT_SIZE(Vector3);
GDCC_GODOT_ASSERT_SIZE(Vector3i);
GDCC_GODOT_ASSERT_SIZE(Transform2D);
GDCC_GODOT_ASSERT_SIZE(Vector4);
GDCC_GODOT_ASSERT_SIZE(Vector4i);
GDCC_GODOT_ASSERT_SIZE(Plane);
GDCC_GODOT_ASSERT_SIZE(Quaternion);
GDCC_GODOT_ASSERT_SIZE(AABB);
GDCC_GODOT_ASSERT_SIZE(Basis);
GDCC_GODOT_ASSERT_SIZE(Transform3D);
GDCC_GODOT_ASSERT_SIZE(Projection);
GDCC_GODOT_ASSERT_SIZE(Color);
GDCC_GODOT_ASSERT_SIZE(StringName);
GDCC_GODOT_ASSERT_SIZE(NodePath);
GDCC_GODOT_ASSERT_SIZE(RID);
GDCC_GODOT_ASSERT_SIZE(Callable);
GDCC_GODOT_ASSERT_SIZE(Signal);
GDCC_GODOT_ASSERT_SIZE(Dictionary);
GDCC_GODOT_ASSERT_SIZE(Array);
GDCC_GODOT_ASSERT_SIZE(PackedByteArray);
GDCC_GODOT_ASSERT_SIZE(PackedInt32Array);
GDCC_GODOT_ASSERT_SIZE(PackedInt64Array);
GDCC_GODOT_ASSERT_SIZE(PackedFloat32Array);
GDCC_GODOT_ASSERT_SIZE(PackedFloat64Array);
GDCC_GODOT_ASSERT_SIZE(PackedStringArray);
GDCC_GODOT_ASSERT_SIZE(PackedVector2Array);
GDCC_GODOT_ASSERT_SIZE(PackedVector3Array);
GDCC_GODOT_ASSERT_SIZE(PackedColorArray);
GDCC_GODOT_ASSERT_SIZE(PackedVector4Array);
GDCC_GODOT_ASSERT_SIZE(Variant);
GDCC_GODOT_ASSERT_LAYOUT(Vector2, x);
GDCC_GODOT_ASSERT_LAYOUT(Vector2, y);
GDCC_GODOT_ASSERT_LAYOUT(Vector2i, x);
GDCC_GODOT_ASSERT_LAYOUT(Vector2i, y);
GDCC_GODOT_ASSERT_LAYOUT(Rect2, position);
GDCC_GODOT_ASSERT_LAYOUT(Rect2, size);
GDCC_GODOT_ASSERT_LAYOUT(Rect2i, position);
GDCC_GODOT_ASSERT_LAYOUT(Rect2i, size);
GDCC_GODOT_ASSERT_LAYOUT(Vector3, x);
GDCC_GODOT_ASSERT_LAYOUT(Vector3, y);
GDCC_GODOT_ASSERT_LAYOUT(Vector3, z);
GDCC_GODOT_ASSERT_LAYOUT(Vector3i, x);
GDCC_GODOT_ASSERT_LAYOUT(Vector3i, y);
GDCC_GODOT_ASSERT_LAYOUT(Vector3i, z);
GDCC_GODOT_ASSERT_LAYOUT(Transform2D, x);
GDCC_GODOT_ASSERT_LAYOUT(Transform2D, y);
GDCC_GODOT_ASSERT_LAYOUT(Transform2D, origin);
GDCC_GODOT_ASSERT_LAYOUT(Vector4, x);
GDCC_GODOT_ASSERT_LAYOUT(Vector4, y);
GDCC_GODOT_ASSERT_LAYOUT(Vector4, z);
GDCC_GODOT_ASSERT_LAYOUT(Vector4, w);
GDCC_GODOT_ASSERT_LAYOUT(Vector4i, x);
GDCC_GODOT_ASSERT_LAYOUT(Vector4i, y);
GDCC_GODOT_ASSERT_LAYOUT(Vector4i, z);
GDCC_GODOT_ASSERT_LAYOUT(Vector4i, w);
GDCC_GODOT_ASSERT_LAYOUT(Plane, normal);
GDCC_GODOT_ASSERT_LAYOUT(Plane, d);
GDCC_GODOT_ASSERT_LAYOUT(Quaternion, x);
GDCC_GODOT_ASSERT_LAYOUT(Quaternion, y);
GDCC_GODOT_ASSERT_LAYOUT(Quaternion, z);
GDCC_GODOT_ASSERT_LAYOUT(Quaternion, w);
GDCC_GODOT_ASSERT_LAYOUT(AABB, position);
GDCC_GODOT_ASSERT_LAYOUT(AABB, size);
GDCC_GODOT_ASSERT_LAYOUT(Basis, x);
GDCC_GODOT_ASSERT_LAYOUT(Basis, y);
GDCC_GODOT_ASSERT_LAYOUT(Basis, z);
GDCC_GODOT_ASSERT_LAYOUT(Transform3D, basis);
GDCC_GODOT_ASSERT_LAYOUT(Transform3D, origin);
GDCC_GODOT_ASSERT_LAYOUT(Projection, x);
GDCC_GODOT_ASSERT_LAYOUT(Projection, y);
GDCC_GODOT_ASSERT_LAYOUT(Projection, z);
GDCC_GODOT_ASSERT_LAYOUT(Projection, w);
GDCC_GODOT_ASSERT_LAYOUT(Color, r);
GDCC_GODOT_ASSERT_LAYOUT(Color, g);
GDCC_GODOT_ASSERT_LAYOUT(Color, b);
GDCC_GODOT_ASSERT_LAYOUT(Color, a);

#endif
