/* This file was generated by GodotInterfaceGenerator. */
/* Do not edit by hand. */
#ifndef GDCC_GODOT_BINDING_H
#define GDCC_GODOT_BINDING_H

#include <godot_abi.h>
#include <godot_interface.h>
#include <godot_builtin.h>
#include <godot_utility.h>
#include <godot_fixed_binding.h>

#endif
