/* This file was generated by GodotBindingTool. */
/* Do not edit by hand. */
#ifndef GDCC_GODOT_BUILTIN_SIZES_H
#define GDCC_GODOT_BUILTIN_SIZES_H

#include <stdint.h>

/* GDCC supports only Godot float_64 ABI: 64-bit pointers with single-precision real_t. */
#ifdef REAL_T_IS_DOUBLE
#error "GDCC C backend supports only single-precision Godot real_t builds"
#endif

#if INTPTR_MAX == INT64_MAX
#define GDCC_GODOT_BUILD_FLOAT_64
#elif INTPTR_MAX == INT32_MAX
#error "GDCC C backend does not support 32-bit Godot builtin ABI"
#else
#error "Unsupported pointer width for Godot builtin ABI sizes"
#endif

#ifdef GDCC_GODOT_BUILD_FLOAT_64
#define GDCC_GODOT_SIZE_Nil 0
#define GDCC_GODOT_SIZE_bool 1
#define GDCC_GODOT_SIZE_int 8
#define GDCC_GODOT_SIZE_float 8
#define GDCC_GODOT_SIZE_String 8
#define GDCC_GODOT_SIZE_Vector2 8
#define GDCC_GODOT_SIZE_Vector2i 8
#define GDCC_GODOT_SIZE_Rect2 16
#define GDCC_GODOT_SIZE_Rect2i 16
#define GDCC_GODOT_SIZE_Vector3 12
#define GDCC_GODOT_SIZE_Vector3i 12
#define GDCC_GODOT_SIZE_Transform2D 24
#define GDCC_GODOT_SIZE_Vector4 16
#define GDCC_GODOT_SIZE_Vector4i 16
#define GDCC_GODOT_SIZE_Plane 16
#define GDCC_GODOT_SIZE_Quaternion 16
#define GDCC_GODOT_SIZE_AABB 24
#define GDCC_GODOT_SIZE_Basis 36
#define GDCC_GODOT_SIZE_Transform3D 48
#define GDCC_GODOT_SIZE_Projection 64
#define GDCC_GODOT_SIZE_Color 16
#define GDCC_GODOT_SIZE_StringName 8
#define GDCC_GODOT_SIZE_NodePath 8
#define GDCC_GODOT_SIZE_RID 8
#define GDCC_GODOT_SIZE_Object 8
#define GDCC_GODOT_SIZE_Callable 16
#define GDCC_GODOT_SIZE_Signal 16
#define GDCC_GODOT_SIZE_Dictionary 8
#define GDCC_GODOT_SIZE_Array 8
#define GDCC_GODOT_SIZE_PackedByteArray 16
#define GDCC_GODOT_SIZE_PackedInt32Array 16
#define GDCC_GODOT_SIZE_PackedInt64Array 16
#define GDCC_GODOT_SIZE_PackedFloat32Array 16
#define GDCC_GODOT_SIZE_PackedFloat64Array 16
#define GDCC_GODOT_SIZE_PackedStringArray 16
#define GDCC_GODOT_SIZE_PackedVector2Array 16
#define GDCC_GODOT_SIZE_PackedVector3Array 16
#define GDCC_GODOT_SIZE_PackedColorArray 16
#define GDCC_GODOT_SIZE_PackedVector4Array 16
#define GDCC_GODOT_SIZE_Variant 24
#endif

#endif
