/* This file was generated by GodotBindingTool. */
/* Do not edit by hand. */
#ifndef GDCC_GODOT_ABI_H
#define GDCC_GODOT_ABI_H

#include <gdextension/gdextension_interface.h>
#include <godot_macros.h>
#include <godot_global_enums.h>
#include <godot_global_constants.h>
#include <godot_builtin_sizes.h>
#include <godot_builtin_layout.h>
#include <godot_builtin_types.h>
#include <godot_native_structures.h>

#endif
