package dev.superice.gdcc.lir.validation;

import dev.superice.gdcc.backend.CodegenContext;
import dev.superice.gdcc.backend.ProjectInfo;
import dev.superice.gdcc.enums.GodotVersion;
import dev.superice.gdcc.enums.LifecycleProvenance;
import dev.superice.gdcc.exception.InvalidInsnException;
import dev.superice.gdcc.gdextension.ExtensionAPI;
import dev.superice.gdcc.lir.LirBasicBlock;
import dev.superice.gdcc.lir.LirFunctionDef;
import dev.superice.gdcc.lir.insn.DestructInsn;
import dev.superice.gdcc.lir.insn.TryOwnObjectInsn;
import dev.superice.gdcc.lir.insn.TryReleaseObjectInsn;
import dev.superice.gdcc.scope.ClassRegistry;
import dev.superice.gdcc.type.GdObjectType;
import dev.superice.gdcc.type.GdStringType;
import dev.superice.gdcc.type.GdVoidType;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class LifecycleInstructionRestrictionValidatorTest {
    private final LifecycleInstructionRestrictionValidator validator = new LifecycleInstructionRestrictionValidator();

    @Test
    @DisplayName("UNKNOWN provenance should fail in strict mode")
    void unknownProvenanceShouldFailInStrictMode() {
        var func = newFunction("strict_unknown");
        func.createAndAddVariable("value", GdStringType.STRING);
        var entry = new LirBasicBlock("entry");
        entry.instructions().add(new DestructInsn("value"));
        func.addBasicBlock(entry);

        var ex = assertThrows(InvalidInsnException.class,
                () -> validator.validateFunction(newContext(true), func));
        assertInstanceOf(InvalidInsnException.class, ex);
        assertTrue(ex.getMessage().contains("UNKNOWN"));
        assertTrue(ex.getMessage().contains("value"));
    }

    @Test
    @DisplayName("UNKNOWN provenance should pass in compat mode")
    void unknownProvenanceShouldPassInCompatMode() {
        var func = newFunction("compat_unknown");
        func.createAndAddVariable("value", GdStringType.STRING);
        var entry = new LirBasicBlock("entry");
        entry.instructions().add(new DestructInsn("value"));
        func.addBasicBlock(entry);

        assertDoesNotThrow(() -> validator.validateFunction(newContext(false), func));
    }

    @Test
    @DisplayName("AUTO_GENERATED should only be allowed in __finally__ destruct")
    void autoGeneratedShouldRequireFinallyDestruct() {
        var invalidFunc = newFunction("invalid_auto_generated");
        invalidFunc.createAndAddVariable("value", GdStringType.STRING);
        var invalidEntry = new LirBasicBlock("entry");
        invalidEntry.instructions().add(new DestructInsn("value", LifecycleProvenance.AUTO_GENERATED));
        invalidFunc.addBasicBlock(invalidEntry);

        var invalidEx = assertThrows(InvalidInsnException.class,
                () -> validator.validateFunction(newContext(true), invalidFunc));
        assertInstanceOf(InvalidInsnException.class, invalidEx);
        assertTrue(invalidEx.getMessage().contains("__finally__"));

        var validFunc = newFunction("valid_auto_generated");
        validFunc.createAndAddVariable("value", GdStringType.STRING);
        var finallyBlock = new LirBasicBlock("__finally__");
        finallyBlock.instructions().add(new DestructInsn("value", LifecycleProvenance.AUTO_GENERATED));
        validFunc.addBasicBlock(finallyBlock);
        validFunc.setEntryBlockId("__finally__");

        assertDoesNotThrow(() -> validator.validateFunction(newContext(true), validFunc));
    }

    @Test
    @DisplayName("INTERNAL provenance should only allow compiler temp/internal variables")
    void internalProvenanceShouldRequireInternalVariable() {
        var validFunc = newFunction("valid_internal");
        validFunc.createAndAddTmpVariable(GdStringType.STRING);
        var validEntry = new LirBasicBlock("entry");
        validEntry.instructions().add(new DestructInsn("0", LifecycleProvenance.INTERNAL));
        validFunc.addBasicBlock(validEntry);

        assertDoesNotThrow(() -> validator.validateFunction(newContext(true), validFunc));

        var invalidFunc = newFunction("invalid_internal");
        invalidFunc.createAndAddVariable("namedVar", GdStringType.STRING);
        var invalidEntry = new LirBasicBlock("entry");
        invalidEntry.instructions().add(new DestructInsn("namedVar", LifecycleProvenance.INTERNAL));
        invalidFunc.addBasicBlock(invalidEntry);

        var ex = assertThrows(InvalidInsnException.class,
                () -> validator.validateFunction(newContext(true), invalidFunc));
        assertInstanceOf(InvalidInsnException.class, ex);
        assertTrue(ex.getMessage().contains("namedVar"));
    }

    @Test
    @DisplayName("USER_EXPLICIT provenance should be allowed by default in non auto-generated blocks")
    void userExplicitProvenanceShouldBeAllowedByDefault() {
        var validFunc = newFunction("valid_user_explicit");
        validFunc.createAndAddVariable("obj", new GdObjectType("Object"));
        var validEntry = new LirBasicBlock("entry");
        validEntry.instructions().add(new TryReleaseObjectInsn("obj", LifecycleProvenance.USER_EXPLICIT));
        validFunc.addBasicBlock(validEntry);

        assertDoesNotThrow(() -> validator.validateFunction(newContext(true), validFunc));

        var invalidFunc = newFunction("invalid_user_explicit_in_finally");
        invalidFunc.createAndAddVariable("obj", new GdObjectType("Object"));
        var invalidFinally = new LirBasicBlock("__finally__");
        invalidFinally.instructions().add(new TryOwnObjectInsn("obj", LifecycleProvenance.USER_EXPLICIT));
        invalidFunc.addBasicBlock(invalidFinally);
        invalidFunc.setEntryBlockId("__finally__");

        var ex = assertThrows(InvalidInsnException.class,
                () -> validator.validateFunction(newContext(true), invalidFunc));
        assertInstanceOf(InvalidInsnException.class, ex);
        assertTrue(ex.getMessage().contains("__finally__"));
    }

    private static LirFunctionDef newFunction(String name) {
        var func = new LirFunctionDef(name);
        func.setReturnType(GdVoidType.VOID);
        func.setEntryBlockId("entry");
        return func;
    }

    private static CodegenContext newContext(boolean strictMode) {
        var api = new ExtensionAPI(null, List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of());
        var classRegistry = new ClassRegistry(api);
        ProjectInfo projectInfo = new ProjectInfo("TestProject", GodotVersion.V451, Path.of(".")) {
        };
        return new CodegenContext(projectInfo, classRegistry, strictMode);
    }
}
