package dev.superice.gdcc.lir.validation;

import dev.superice.gdcc.backend.CodegenContext;
import dev.superice.gdcc.exception.InvalidInsnException;
import dev.superice.gdcc.lir.LirBasicBlock;
import dev.superice.gdcc.lir.LirFunctionDef;
import dev.superice.gdcc.lir.insn.DestructInsn;
import dev.superice.gdcc.lir.insn.LifecycleInstruction;
import dev.superice.gdcc.lir.insn.TryOwnObjectInsn;
import dev.superice.gdcc.lir.insn.TryReleaseObjectInsn;
import org.jetbrains.annotations.NotNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/// Validates lifecycle-instruction provenance before backend code generation.
///
/// This validator enforces controlled usage for:
/// - `destruct`
/// - `try_own_object`
/// - `try_release_object`
public final class LifecycleInstructionRestrictionValidator {
    private static final Logger LOGGER = LoggerFactory.getLogger(LifecycleInstructionRestrictionValidator.class);

    public void validateFunction(@NotNull CodegenContext ctx, @NotNull LirFunctionDef func) {
        for (var block : func) {
            validateBlock(ctx, func, block);
        }
    }

    private void validateBlock(@NotNull CodegenContext ctx,
                               @NotNull LirFunctionDef func,
                               @NotNull LirBasicBlock block) {
        for (int index = 0; index < block.instructions().size(); index++) {
            var insn = block.instructions().get(index);
            if (!(insn instanceof LifecycleInstruction lifecycleInsn)) {
                continue;
            }
            validateLifecycleInstruction(ctx, func, block, index, lifecycleInsn);
        }
    }

    private void validateLifecycleInstruction(@NotNull CodegenContext ctx,
                                              @NotNull LirFunctionDef func,
                                              @NotNull LirBasicBlock block,
                                              int index,
                                              @NotNull LifecycleInstruction insn) {
        var variableId = resolveVariableId(insn);
        var provenance = insn.getProvenance();
        switch (provenance) {
            case UNKNOWN -> validateUnknownProvenance(ctx, func, block, index, insn, variableId);
            case AUTO_GENERATED -> validateAutoGenerated(func, block, index, insn, variableId);
            case INTERNAL -> validateInternal(func, block, index, insn, variableId);
            case USER_EXPLICIT -> validateUserExplicit(func, block, index, insn, variableId);
        }
    }

    private void validateUnknownProvenance(@NotNull CodegenContext ctx,
                                           @NotNull LirFunctionDef func,
                                           @NotNull LirBasicBlock block,
                                           int index,
                                           @NotNull LifecycleInstruction insn,
                                           @NotNull String variableId) {
        if (ctx.strictMode()) {
            throw invalidInsn(func, block, index, insn,
                    "Lifecycle provenance UNKNOWN is forbidden in strict mode (variable '" + variableId + "')");
        }
        LOGGER.warn("Lifecycle provenance UNKNOWN in compat mode: function='{}', block='{}', index={}, insn='{}', variable='{}'",
                func.getName(), block.id(), index, insn.opcode().opcode(), variableId);
    }

    private void validateAutoGenerated(@NotNull LirFunctionDef func,
                                       @NotNull LirBasicBlock block,
                                       int index,
                                       @NotNull LifecycleInstruction insn,
                                       @NotNull String variableId) {
        if (!(insn instanceof DestructInsn)) {
            throw invalidInsn(func, block, index, insn,
                    "AUTO_GENERATED is only valid for destruct in __finally__ (variable '" + variableId + "')");
        }
        if (!"__finally__".equals(block.id())) {
            throw invalidInsn(func, block, index, insn,
                    "AUTO_GENERATED lifecycle instruction must be in __finally__ (variable '" + variableId + "')");
        }
    }

    private void validateInternal(@NotNull LirFunctionDef func,
                                  @NotNull LirBasicBlock block,
                                  int index,
                                  @NotNull LifecycleInstruction insn,
                                  @NotNull String variableId) {
        var variable = func.getVariableById(variableId);
        if (variable == null) {
            throw invalidInsn(func, block, index, insn,
                    "INTERNAL lifecycle instruction references unknown variable '" + variableId + "'");
        }
        if (func.checkVariableParameter(variableId)) {
            throw invalidInsn(func, block, index, insn,
                    "INTERNAL lifecycle instruction cannot target parameter variable '" + variableId + "'");
        }
        if (!isInternalVariableId(variableId)) {
            throw invalidInsn(func, block, index, insn,
                    "INTERNAL lifecycle instruction must target compiler temp/internal variable, got '" + variableId + "'");
        }
    }

    private void validateUserExplicit(@NotNull LirFunctionDef func,
                                      @NotNull LirBasicBlock block,
                                      int index,
                                      @NotNull LifecycleInstruction insn,
                                      @NotNull String variableId) {
        if ("__prepare__".equals(block.id()) || "__finally__".equals(block.id())) {
            throw invalidInsn(func, block, index, insn,
                    "USER_EXPLICIT lifecycle instruction is not allowed in auto-generated block '" + block.id() +
                            "' (variable '" + variableId + "')");
        }
    }

    private static boolean isInternalVariableId(@NotNull String variableId) {
        if (variableId.startsWith("__")) {
            return true;
        }
        for (int i = 0; i < variableId.length(); i++) {
            if (!Character.isDigit(variableId.charAt(i))) {
                return false;
            }
        }
        return !variableId.isEmpty();
    }

    private static @NotNull String resolveVariableId(@NotNull LifecycleInstruction insn) {
        return switch (insn) {
            case DestructInsn destructInsn -> destructInsn.variableId();
            case TryOwnObjectInsn tryOwnObjectInsn -> tryOwnObjectInsn.objectId();
            case TryReleaseObjectInsn tryReleaseObjectInsn -> tryReleaseObjectInsn.objectId();
            default -> throw new IllegalStateException("Unsupported lifecycle instruction: " + insn.getClass().getName());
        };
    }

    private static @NotNull InvalidInsnException invalidInsn(@NotNull LirFunctionDef func,
                                                             @NotNull LirBasicBlock block,
                                                             int index,
                                                             @NotNull LifecycleInstruction insn,
                                                             @NotNull String reason) {
        return new InvalidInsnException(func.getName(), block.id(), index, insn.opcode().opcode(), reason);
    }
}
